var SQL = function(SQL) {
  SQL = SQL || {};

var e;e||(e=typeof SQL !== 'undefined' ? SQL : {});var h;e.ENVIRONMENT="WEB";h={X:0,Yc:1,rd:2,Bd:3,jb:4,lb:5,ud:6,NOMEM:7,Ed:8,sd:9,td:10,ob:11,NOTFOUND:12,qd:13,mb:14,Cd:15,EMPTY:16,Fd:17,Gd:18,nb:19,vd:20,wd:21,xd:22,kb:23,pd:24,Dd:25,yd:26,zd:27,Hd:28,Ia:100,DONE:101,Ha:1,FLOAT:2,Ja:3,Ea:4,Ad:5,Ka:1};
e.onRuntimeInitialized=function(){var a=aa(4);var b=function(){function a(a,b){this.j=a;this.db=b;this.C=1;this.ha=[]}a.prototype.bind=function(a){if(!this.j)throw"Statement closed";this.reset();return Array.isArray(a)?this.Oa(a):this.Pa(a)};a.prototype.step=function(){var a;if(!this.j)throw"Statement closed";this.C=1;switch(a=Ua(this.j)){case h.Ia:return!0;case h.DONE:return!1;default:return this.db.handleError(a)}};a.prototype.Va=function(a){null==a&&(a=this.C++);return mc(this.j,a)};a.prototype.Wa=
function(a){null==a&&(a=this.C++);return nc(this.j,a)};a.prototype.getBlob=function(a){var b;null==a&&(a=this.C++);var c=oc(this.j,a);var d=pc(this.j,a);var f=new Uint8Array(c);for(a=b=0;0<=c?b<c:b>c;a=0<=c?++b:--b)f[a]=k[d+a];return f};a.prototype.get=function(a){var b,c;null!=a&&this.bind(a)&&this.step();var d=[];a=b=0;for(c=Ab(this.j);0<=c?b<c:b>c;a=0<=c?++b:--b)switch(qc(this.j,a)){case h.Ha:case h.FLOAT:d.push(this.Va(a));break;case h.Ja:d.push(this.Wa(a));break;case h.Ea:d.push(this.getBlob(a));
break;default:d.push(null)}return d};a.prototype.getColumnNames=function(){var a,b;var c=[];var d=a=0;for(b=Ab(this.j);0<=b?a<b:a>b;d=0<=b?++a:--a)c.push(rc(this.j,d));return c};a.prototype.getAsObject=function(a){var b,c;var d=this.get(a);var f=this.getColumnNames();var g={};a=b=0;for(c=f.length;b<c;a=++b){var t=f[a];g[t]=d[a]}return g};a.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};a.prototype.Sa=function(a,b){var c;null==b&&(b=this.C++);a=ba(a);this.ha.push(c=
ca(a,da));this.db.handleError(w(this.j,b,c,a.length-1,0))};a.prototype.Na=function(a,b){var c;null==b&&(b=this.C++);this.ha.push(c=ca(a,da));this.db.handleError(u(this.j,b,c,a.length,0))};a.prototype.Ra=function(a,b){null==b&&(b=this.C++);this.db.handleError((a===(a|0)?ja:K)(this.j,b,a))};a.prototype.Qa=function(a){null==a&&(a=this.C++);u(this.j,a,0,0,0)};a.prototype.ta=function(a,b){null==b&&(b=this.C++);switch(typeof a){case "string":this.Sa(a,b);break;case "number":case "boolean":this.Ra(a+0,b);
break;case "object":if(null===a)this.Qa(b);else if(null!=a.length)this.Na(a,b);else throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};a.prototype.Pa=function(a){var b;for(b in a){var c=a[b];var d=t(this.j,b);0!==d&&this.ta(c,d)}return!0};a.prototype.Oa=function(a){var b,c;var d=b=0;for(c=a.length;b<c;d=++b){var f=a[d];this.ta(f,d+1)}return!0};a.prototype.reset=function(){this.freemem();return sc(this.j)===h.X&&tc(this.j)===h.X};a.prototype.freemem=function(){for(var a;a=
this.ha.pop();)ea(a);return null};a.prototype.free=function(){this.freemem();var a=uc(this.j)===h.X;delete this.db.ba[this.j];this.j=0;return a};return a}();var c=function(){function c(b){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=b){var c=this.filename,f=c?m("/",c):"/";c=fa(!0,!0);f=ha(f,(void 0!==c?c:438)&4095|32768,0);if(b){if("string"===typeof b){for(var g=Array(b.length),t=0,l=b.length;t<l;++t)g[t]=b.charCodeAt(t);b=g}ia(f,c|146);g=n(f,"w");ka(g,b,0,b.length,0,void 0);la(g);
ia(f,c)}}this.handleError(d(this.filename,a));this.db=p(a,"i32");vc(this.db);this.ba={}}c.prototype.run=function(b,c){if(!this.db)throw"Database closed";c?(b=this.prepare(b,c),b.step(),b.free()):this.handleError(g(this.db,b,0,0,a));return this};c.prototype.exec=function(c){if(!this.db)throw"Database closed";var d=ma();var f=c.length<<3;var g=aa(f);na(c,q,g,f);c=aa(4);for(f=[];0!==p(g,"i8");){oa(a);oa(c);this.handleError(y(this.db,g,-1,a,c));var t=p(a,"i32");g=p(c,"i32");if(0!==t){var l=new b(t,this);
for(t=null;l.step();)null===t&&(t={columns:l.getColumnNames(),values:[]},f.push(t)),t.values.push(l.get());l.free()}}pa(d);return f};c.prototype.each=function(a,b,c,d){"function"===typeof b&&(d=c,c=b,b=void 0);for(a=this.prepare(a,b);a.step();)c(a.getAsObject());a.free();if("function"===typeof d)return d()};c.prototype.prepare=function(c,d){oa(a);this.handleError(r(this.db,c,-1,a,0));c=p(a,"i32");if(0===c)throw"Nothing to prepare";var f=new b(c,this);null!=d&&f.bind(d);return this.ba[c]=f};c.prototype["export"]=
function(){var b;var c=this.ba;for(t in c){var g=c[t];g.free()}this.handleError(f(this.db));g=this.filename;var t=t={encoding:"binary"};t.flags=t.flags||"r";t.encoding=t.encoding||"binary";if("utf8"!==t.encoding&&"binary"!==t.encoding)throw Error('Invalid encoding type "'+t.encoding+'"');c=n(g,t.flags);g=qa(g).size;var l=new Uint8Array(g);ra(c,l,0,g,0);"utf8"===t.encoding?b=sa(l,0):"binary"===t.encoding&&(b=l);la(c);this.handleError(d(this.filename,a));this.db=p(a,"i32");return b};c.prototype.close=
function(){var a;var b=this.ba;for(a in b){var c=b[a];c.free()}this.handleError(f(this.db));ta("/"+this.filename);return this.db=null};c.prototype.handleError=function(a){if(a===h.X)return null;a=wc(this.db);throw Error(a);};c.prototype.getRowsModified=function(){return l(this.db)};c.prototype.create_function=function(a,b){var c=ua(function(a,c,d){var f,g;var t=[];for(f=g=0;0<=c?g<c:g>c;f=0<=c?++g:--g){var l=p(d+4*f,"i32");var u=yc(l);f=function(){switch(!1){case 1!==u:return zc;case 2!==u:return Ac;
case 3!==u:return Bc;case 4!==u:return function(a){var b,c;var d=Cc(a);var f=Dc(a);a=new Uint8Array(d);for(b=c=0;0<=d?c<d:c>d;b=0<=d?++c:--c)a[b]=k[f+b];return a};default:return function(){return null}}}();f=f(l);t.push(f)}if(c=b.apply(null,t))switch(typeof c){case "number":return Ec(a,c);case "string":return Fc(a,c,-1,-1)}else return Gc(a)});this.handleError(Hc(this.db,a,b.length,h.Ka,0,c,0,0,0));return this};return c}();var d=e.cwrap("sqlite3_open","number",["string","number"]);var f=e.cwrap("sqlite3_close_v2",
"number",["number"]);var g=e.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);e.cwrap("sqlite3_free","",["number"]);var l=e.cwrap("sqlite3_changes","number",["number"]);var r=e.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);var y=e.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);var w=e.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);var u=e.cwrap("sqlite3_bind_blob",
"number",["number","number","number","number","number"]);var K=e.cwrap("sqlite3_bind_double","number",["number","number","number"]);var ja=e.cwrap("sqlite3_bind_int","number",["number","number","number"]);var t=e.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);var Ua=e.cwrap("sqlite3_step","number",["number"]);var wc=e.cwrap("sqlite3_errmsg","string",["number"]);var Ab=e.cwrap("sqlite3_data_count","number",["number"]);var mc=e.cwrap("sqlite3_column_double","number",["number","number"]);
var nc=e.cwrap("sqlite3_column_text","string",["number","number"]);var pc=e.cwrap("sqlite3_column_blob","number",["number","number"]);var oc=e.cwrap("sqlite3_column_bytes","number",["number","number"]);var qc=e.cwrap("sqlite3_column_type","number",["number","number"]);var rc=e.cwrap("sqlite3_column_name","string",["number","number"]);var tc=e.cwrap("sqlite3_reset","number",["number"]);var sc=e.cwrap("sqlite3_clear_bindings","number",["number"]);var uc=e.cwrap("sqlite3_finalize","number",["number"]);
var Hc=e.cwrap("sqlite3_create_function_v2","number","number string number number number number number number number".split(" "));var yc=e.cwrap("sqlite3_value_type","number",["number"]);var Cc=e.cwrap("sqlite3_value_bytes","number",["number"]);var Bc=e.cwrap("sqlite3_value_text","string",["number"]);var zc=e.cwrap("sqlite3_value_int","number",["number"]);var Dc=e.cwrap("sqlite3_value_blob","number",["number"]);var Ac=e.cwrap("sqlite3_value_double","number",["number"]);var Ec=e.cwrap("sqlite3_result_double",
"",["number","number"]);var Gc=e.cwrap("sqlite3_result_null","",["number"]);var Fc=e.cwrap("sqlite3_result_text","",["number","string","number","number"]);var vc=e.cwrap("RegisterExtensionFunctions","number",["number"]);return e.SQL={Database:c}};var va={},v;for(v in e)e.hasOwnProperty(v)&&(va[v]=e[v]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var x=!1,z=!1,A=!1,wa=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)x=!0;else if("WORKER"===e.ENVIRONMENT)z=!0;else if("NODE"===e.ENVIRONMENT)A=!0;else if("SHELL"===e.ENVIRONMENT)wa=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else x="object"===typeof window,z="function"===typeof importScripts,A="object"===typeof process&&"function"===typeof require&&!x&&!z,wa=!x&&!A&&!z;
if(A){var xa,ya;e.read=function(a,b){xa||(xa=require("fs"));ya||(ya=require("path"));a=ya.normalize(a);a=xa.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof za))throw a;});process.on("unhandledRejection",function(){process.exit(1)});e.inspect=
function(){return"[Emscripten Module object]"}}else if(wa)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(x||z)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},z&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),e.setWindowTitle=function(a){document.title=a};
e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(v in va)va.hasOwnProperty(v)&&(e[v]=va[v]);va=void 0;function Aa(a){assert(!Ba);var b=B;B=B+a+15&-16;return b}function Ca(a){assert(C);var b=D[C>>2];a=b+a+15&-16;D[C>>2]=a;if(a=a>=E)Da(),a=!0;return a?(D[C>>2]=b,0):b}
function Ea(a){var b;b||(b=16);return Math.ceil(a/b)*b}var Fa=1,F=Array(64);function ua(a){for(var b=0;64>b;b++)if(!F[b])return F[b]=a,Fa+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";}var Ga=0;function assert(a,b){a||G("Assertion failed: "+b)}function Ha(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
var Ia={stackSave:function(){ma()},stackRestore:function(){pa()},arrayToC:function(a){var b=aa(a.length);k.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=aa(c);na(a,q,b,c)}return b}},Ja={string:Ia.stringToC,array:Ia.arrayToC};
function oa(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":k[a>>0]=0;break;case "i8":k[a>>0]=0;break;case "i16":Ka[a>>1]=0;break;case "i32":D[a>>2]=0;break;case "i64":tempI64=[0,(tempDouble=0,1<=+La(tempDouble)?0<tempDouble?(Ma(+Na(tempDouble/4294967296),4294967295)|0)>>>0:~~+Oa((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];D[a>>2]=tempI64[0];D[a+4>>2]=tempI64[1];break;case "float":Pa[a>>2]=0;break;case "double":Qa[a>>3]=0;break;default:G("invalid type for setValue: "+
b)}}function p(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return k[a>>0];case "i8":return k[a>>0];case "i16":return Ka[a>>1];case "i32":return D[a>>2];case "i64":return D[a>>2];case "float":return Pa[a>>2];case "double":return Qa[a>>3];default:G("invalid type for getValue: "+b)}return null}var da=0,Ra=2,Sa=4;
function ca(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=b==Sa?f:["function"===typeof Ta?Ta:Aa,aa,Aa,Ca][void 0===b?Ra:b](Math.max(d,1));if(c){var f=b;assert(0==(b&3));for(a=b+(d&-4);f<a;f+=4)D[f>>2]=0;for(a=b+d;f<a;)k[f++>>0]=0;return b}a.subarray||a.slice?q.set(a,b):q.set(new Uint8Array(a),b);return b}
function H(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=q[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,q.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return sa(q,a)}var Va="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Va)return Va.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var l=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|l;else{var r=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|l<<6|r;else{var y=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|l<<12|r<<6|y}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function na(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);55296<=l&&57343>=l&&(l=65536+((l&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(2097151>=l){if(c+3>=d)break;b[c++]=240|l>>18}else{if(67108863>=l){if(c+4>=d)break;b[c++]=248|l>>24}else{if(c+5>=d)break;b[c++]=252|l>>30;b[c++]=128|l>>24&63}b[c++]=128|l>>18&63}b[c++]=128|
l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}function Wa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Xa(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}var buffer,k,q,Ka,D,Pa,Qa;
function Ya(){e.HEAP8=k=new Int8Array(buffer);e.HEAP16=Ka=new Int16Array(buffer);e.HEAP32=D=new Int32Array(buffer);e.HEAPU8=q=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=Pa=new Float32Array(buffer);e.HEAPF64=Qa=new Float64Array(buffer)}var Za,B,Ba,$a,ab,bb,cb,C;Za=B=$a=ab=bb=cb=C=0;Ba=!1;
function Da(){G("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+E+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var db=e.TOTAL_STACK||5242880,E=e.TOTAL_MEMORY||16777216;E<db&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+E+"! (TOTAL_STACK="+db+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:E/65536,maximum:E/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(E),e.buffer=buffer);Ya();D[0]=1668509029;Ka[1]=25459;if(115!==q[2]||99!==q[3])throw"Runtime error: expected the system to be little-endian!";
function eb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Id;"number"===typeof c?void 0===b.ia?e.dynCall_v(c):e.dynCall_vi(c,b.ia):c(void 0===b.ia?null:b.ia)}}}var fb=[],gb=[],hb=[],ib=[],jb=[],kb=!1;function lb(){var a=e.preRun.shift();fb.unshift(a)}var La=Math.abs,Oa=Math.ceil,Na=Math.floor,Ma=Math.min,I=0,mb=null,nb=null;e.preloadedImages={};e.preloadedAudios={};
function ob(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(u){G(u)}}function b(){return e.wasmBinary||!x&&!z||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){r=a.exports;if(r.memory){a=r.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Ya()}e.asm=r;e.usingWasm=!0;I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==mb&&(clearInterval(mb),mb=null),nb&&(a=nb,nb=null,a()))}
function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,l)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+a);G(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;l.global={NaN:NaN,Infinity:Infinity};l["global.Math"]=Math;l.env=a;I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);
if(e.instantiateWasm)try{return e.instantiateWasm(l,c)}catch(Ua){return e.printErr("Module.instantiateWasm callback failed with error: "+Ua),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||ob(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),l).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="sql-optimized-wasm-raw.wast",
f="sql-optimized-wasm-raw.wasm",g="sql-optimized-wasm-raw.temp.asm.js";"function"===typeof e.locateFile&&(ob(d)||(d=e.locateFile(d)),ob(f)||(f=e.locateFile(f)),ob(g)||(g=e.locateFile(g)));var l={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:e},r=null;e.asmPreload=e.asm;var y=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===w)var b=y(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=
-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(t){b=null;break a}b=void 0}return b};var w="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);
b.tableBase||(b.tableBase=0);(b=c(b))||G("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();Za=1024;B=Za+28832;gb.push();e.STATIC_BASE=Za;e.STATIC_BUMP=28832;B+=16;
var J={B:1,A:2,ad:3,Wb:4,T:5,ra:6,pb:7,uc:8,D:9,Db:10,na:11,md:11,pa:12,N:13,Pb:14,Gc:15,O:16,oa:17,nd:18,U:19,V:20,P:21,h:22,pc:23,Fa:24,Lc:25,jd:26,Qb:27,Cc:28,W:29,Xc:30,ic:31,Rc:32,Mb:33,Ga:34,yc:42,Tb:43,Eb:44,Zb:45,$b:46,ac:47,hc:48,kd:49,sc:50,Yb:51,Jb:35,vc:37,vb:52,yb:53,od:54,qc:55,zb:56,Ab:57,Kb:35,Bb:59,Ec:60,tc:61,ed:62,Dc:63,zc:64,Ac:65,Wc:66,wc:67,sb:68,bd:69,Fb:70,Sc:71,kc:72,Nb:73,xb:74,Mc:76,wb:77,Vc:78,bc:79,cc:80,fc:81,ec:82,dc:83,Fc:38,qa:39,lc:36,fa:40,Nc:95,Qc:96,Ib:104,rc:105,
tb:97,Uc:91,Jc:88,Bc:92,Zc:108,Hb:111,qb:98,Gb:103,oc:101,mc:100,gd:110,Rb:112,Sb:113,Vb:115,ub:114,Lb:89,jc:90,Tc:93,$c:94,rb:99,nc:102,Xb:106,Hc:107,hd:109,ld:87,Ob:122,cd:116,Kc:95,xc:123,Ub:84,Oc:75,Cb:125,Ic:131,Pc:130,dd:86},pb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function qb(a){e.___errno_location&&(D[e.___errno_location()>>2]=a);return a}
function rb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function sb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=rb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function tb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ub(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function vb(){var a=Array.prototype.slice.call(arguments,0);return sb(a.join("/"))}function m(a,b){return sb(a+"/"+b)}
function wb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=rb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var xb=[];function yb(a,b){xb[a]={input:[],output:[],M:b};zb(a,Bb)}
var Bb={open:function(a){var b=xb[a.node.rdev];if(!b)throw new L(J.U);a.tty=b;a.seekable=!1},close:function(a){a.tty.M.flush(a.tty)},flush:function(a){a.tty.M.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.M.Ba)throw new L(J.ra);for(var f=0,g=0;g<d;g++){try{var l=a.tty.M.Ba(a.tty)}catch(r){throw new L(J.T);}if(void 0===l&&0===f)throw new L(J.na);if(null===l||void 0===l)break;f++;b[c+g]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.M.la)throw new L(J.ra);
for(var f=0;f<d;f++)try{a.tty.M.la(a.tty,b[c+f])}catch(g){throw new L(J.T);}d&&(a.node.timestamp=Date.now());return f}},Cb={Ba:function(a){if(!a.input.length){var b=null;if(A){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(l){}}try{d=fs.readSync(f,c,0,256,null)}catch(l){if(-1!=l.toString().indexOf("EOF"))d=0;else throw l;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ba(b,!0)}return a.input.shift()},la:function(a,b){null===b||10===b?(e.print(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(sa(a.output,0)),a.output=[])}},Db={la:function(a,b){null===b||10===b?(e.printErr(sa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(sa(a.output,0)),a.output=[])}},M={v:null,o:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(J.B);M.v||(M.v={dir:{node:{u:M.c.u,l:M.c.l,lookup:M.c.lookup,R:M.c.R,rename:M.c.rename,unlink:M.c.unlink,rmdir:M.c.rmdir,readdir:M.c.readdir,symlink:M.c.symlink},stream:{F:M.f.F}},file:{node:{u:M.c.u,l:M.c.l},stream:{F:M.f.F,read:M.f.read,write:M.f.write,sa:M.f.sa,$:M.f.$,aa:M.f.aa}},link:{node:{u:M.c.u,
l:M.c.l,readlink:M.c.readlink},stream:{}},va:{node:{u:M.c.u,l:M.c.l},stream:Eb}});c=Fb(a,b,c,d);N(c.mode)?(c.c=M.v.dir.node,c.f=M.v.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=M.v.file.node,c.f=M.v.file.stream,c.i=0,c.b=null):40960===(c.mode&61440)?(c.c=M.v.link.node,c.f=M.v.link.stream):8192===(c.mode&61440)&&(c.c=M.v.va.node,c.f=M.v.va.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ua:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.i;++c)b.push(a.b[c]);return b}return a.b},Jd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.i):new Uint8Array(a.b):new Uint8Array},wa:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=M.Ua(a),a.i=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.i&&a.b.set(c.subarray(0,a.i),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},ab:function(a,b){if(a.i!=b)if(0==b)a.b=null,a.i=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.i)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.i=b}},c:{u:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.i:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.H=4096;b.blocks=Math.ceil(b.size/b.H);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.ab(a,b.size)},lookup:function(){throw Gb[J.A];},R:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(g){}if(d)for(var f in d.b)throw new L(J.qa);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=O(a,b),d;for(d in c.b)throw new L(J.qa);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(J.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.i)return 0;a=Math.min(a.node.i-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.i=d;if(0===a.i&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.i=d;if(f+d<=a.i)return a.b.set(b.subarray(c,c+d),f),d}M.wa(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.i=Math.max(a.i,f+d);return d},F:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.i);if(0>b)throw new L(J.h);return b},sa:function(a,b,c){M.wa(a.node,b+c);a.node.i=Math.max(a.node.i,
b+c)},$:function(a,b,c,d,f,g,l){if(32768!==(a.node.mode&61440))throw new L(J.U);c=a.node.b;if(l&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.i)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=Ta(d);if(!d)throw new L(J.pa);b.set(c,d)}else a=!1,d=c.byteOffset;return{$a:d,ga:a}},aa:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new L(J.U);if(f&2)return 0;M.f.write(a,b,0,d,c,!1);return 0}}},P={Z:!1,cb:function(){P.Z=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);P.ya={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ua:function(a){return Buffer.Y?Buffer.from(a):new Buffer(a)},o:function(a){assert(A);return P.createNode(null,"/",P.Aa(a.ka.root),0)},createNode:function(a,b,c){if(!N(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new L(J.h);a=Fb(a,b,c);a.c=P.c;a.f=P.f;return a},Aa:function(a){try{var b=fs.lstatSync(a);P.Z&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new L(J[c.code]);}return b.mode},s:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.o.ka.root);b.reverse();return vb.apply(null,b)},Ta:function(a){a&=-2656257;var b=0,c;for(c in P.ya)a&c&&(b|=P.ya[c],a^=c);if(a)throw new L(J.h);return b},c:{u:function(a){a=P.s(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}P.Z&&!b.H&&(b.H=4096);P.Z&&!b.blocks&&(b.blocks=(b.size+b.H-1)/b.H|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,H:b.H,blocks:b.blocks}},l:function(a,b){var c=P.s(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},lookup:function(a,b){var c=m(P.s(a),b);c=P.Aa(c);return P.createNode(a,b,c)},R:function(a,b,c,d){a=P.createNode(a,b,c,d);b=P.s(a);try{N(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new L(J[f.code]);}return a},rename:function(a,b,c){a=P.s(a);b=m(P.s(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},unlink:function(a,b){a=m(P.s(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},rmdir:function(a,b){a=m(P.s(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},readdir:function(a){a=P.s(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new L(J[b.code]);}},symlink:function(a,
b,c){a=m(P.s(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new L(J[d.code]);}},readlink:function(a){var b=P.s(a);try{return b=fs.readlinkSync(b),b=Hb.relative(Hb.resolve(a.o.ka.root),b)}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}}},f:{open:function(a){var b=P.s(a.node);try{32768===(a.node.mode&61440)&&(a.S=fs.openSync(b,P.Ta(a.flags)))}catch(c){if(!c.code)throw c;throw new L(J[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.S&&fs.closeSync(a.S)}catch(b){if(!b.code)throw b;
throw new L(J[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.S,P.ua(b.buffer),c,d,f)}catch(g){throw new L(J[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.S,P.ua(b.buffer),c,d,f)}catch(g){throw new L(J[g.code]);}},F:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.S).size}catch(d){throw new L(J[d.code]);}if(0>b)throw new L(J.h);return b}}};B+=16;B+=16;B+=16;
var Ib=null,Jb={},Q=[],Kb=1,R=null,Lb=!0,S={},L=null,Gb={};
function T(a,b){a=wb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={za:!0,ma:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ma)throw new L(J.fa);a=rb(a.split("/").filter(function(a){return!!a}),!1);var f=Ib;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=O(f,a[d]);c=m(c,a[d]);f.K&&(!g||g&&b.za)&&(f=f.K.root);if(!g||b.I)for(g=0;40960===(f.mode&61440);)if(f=Mb(c),c=wb(tb(c),f),f=T(c,{ma:b.ma}).node,40<g++)throw new L(J.fa);}return{path:c,node:f}}
function Nb(a){for(var b;;){if(a===a.parent)return a=a.o.Ca,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function Pb(a){var b=Ob(a.parent.id,a.name);a.L=R[b];R[b]=a}function Qb(a){var b=Ob(a.parent.id,a.name);if(R[b]===a)R[b]=a.L;else for(b=R[b];b;){if(b.L===a){b.L=a.L;break}b=b.L}}
function O(a,b){var c;if(c=(c=Rb(a,"x"))?c:a.c.lookup?0:J.N)throw new L(c,a);for(c=R[Ob(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function Fb(a,b,c,d){Sb||(Sb=function(a,b,c,d){a||(a=this);this.parent=a;this.o=a.o;this.K=null;this.id=Kb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Sb.prototype={},Object.defineProperties(Sb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Sb(a,b,c,d);Pb(a);return a}function N(a){return 16384===(a&61440)}
var Tb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ub(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Rb(a,b){if(Lb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return J.N}else return J.N;return 0}function Vb(a,b){try{return O(a,b),J.oa}catch(c){}return Rb(a,"wx")}
function Wb(a,b,c){try{var d=O(a,b)}catch(f){return f.g}if(a=Rb(a,"wx"))return a;if(c){if(!N(d.mode))return J.V;if(d===d.parent||"/"===Nb(d))return J.O}else if(N(d.mode))return J.P;return 0}function Xb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new L(J.Fa);}
function Yb(a,b){Zb||(Zb=function(){},Zb.prototype={},Object.defineProperties(Zb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Zb,d;for(d in a)c[d]=a[d];a=c;b=Xb(b);a.fd=b;return Q[b]=a}var Eb={open:function(a){a.f=Jb[a.node.rdev].f;a.f.open&&a.f.open(a)},F:function(){throw new L(J.W);}};function zb(a,b){Jb[a]={f:b}}
function $b(a,b){var c="/"===b,d=!b;if(c&&Ib)throw new L(J.O);if(!c&&!d){var f=T(b,{za:!1});b=f.path;f=f.node;if(f.K)throw new L(J.O);if(!N(f.mode))throw new L(J.V);}b={type:a,ka:{},Ca:b,Za:[]};a=a.o(b);a.o=b;b.root=a;c?Ib=a:f&&(f.K=b,f.o&&f.o.Za.push(b))}function ha(a,b,c){var d=T(a,{parent:!0}).node;a=ub(a);if(!a||"."===a||".."===a)throw new L(J.h);var f=Vb(d,a);if(f)throw new L(f);if(!d.c.R)throw new L(J.B);return d.c.R(d,a,b,c)}function U(a,b){ha(a,(void 0!==b?b:511)&1023|16384,0)}
function ac(a,b,c){"undefined"===typeof c&&(c=b,b=438);ha(a,b|8192,c)}function bc(a,b){if(!wb(a))throw new L(J.A);var c=T(b,{parent:!0}).node;if(!c)throw new L(J.A);b=ub(b);var d=Vb(c,b);if(d)throw new L(d);if(!c.c.symlink)throw new L(J.B);c.c.symlink(c,b,a)}
function ta(a){var b=T(a,{parent:!0}).node,c=ub(a),d=O(b,c),f=Wb(b,c,!1);if(f)throw new L(f);if(!b.c.unlink)throw new L(J.B);if(d.K)throw new L(J.O);try{S.willDeletePath&&S.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.c.unlink(b,c);Qb(d);try{if(S.onDeletePath)S.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function Mb(a){a=T(a).node;if(!a)throw new L(J.A);if(!a.c.readlink)throw new L(J.h);return wb(Nb(a.parent),a.c.readlink(a))}function qa(a,b){a=T(a,{I:!b}).node;if(!a)throw new L(J.A);if(!a.c.u)throw new L(J.B);return a.c.u(a)}function cc(a){return qa(a,!0)}function ia(a,b){var c;"string"===typeof a?c=T(a,{I:!0}).node:c=a;if(!c.c.l)throw new L(J.B);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function dc(a){var b;"string"===typeof a?b=T(a,{I:!0}).node:b=a;if(!b.c.l)throw new L(J.B);b.c.l(b,{timestamp:Date.now()})}function ec(a,b){if(0>b)throw new L(J.h);var c;"string"===typeof a?c=T(a,{I:!0}).node:c=a;if(!c.c.l)throw new L(J.B);if(N(c.mode))throw new L(J.P);if(32768!==(c.mode&61440))throw new L(J.h);if(a=Rb(c,"w"))throw new L(a);c.c.l(c,{size:b,timestamp:Date.now()})}
function n(a,b,c,d){if(""===a)throw new L(J.A);if("string"===typeof b){var f=Tb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=sb(a);try{g=T(a,{I:!(b&131072)}).node}catch(l){}}f=!1;if(b&64)if(g){if(b&128)throw new L(J.oa);}else g=ha(a,c,0),f=!0;if(!g)throw new L(J.A);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!N(g.mode))throw new L(J.V);if(!f&&(c=g?40960===(g.mode&61440)?J.fa:N(g.mode)&&
("r"!==Ub(b)||b&512)?J.P:Rb(g,Ub(b)):J.A))throw new L(c);b&512&&ec(g,0);b&=-641;d=Yb({node:g,path:Nb(g),flags:b,seekable:!0,position:0,f:g.f,ib:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(fc||(fc={}),a in fc||(fc[a]=1,e.printErr("read file: "+a)));try{S.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),S.onOpenFile(a,g))}catch(l){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}
function la(a){a.ja&&(a.ja=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}}function hc(a,b,c){if(!a.seekable||!a.f.F)throw new L(J.W);a.position=a.f.F(a,b,c);a.ib=[]}function ra(a,b,c,d,f){if(0>d||0>f)throw new L(J.h);if(1===(a.flags&2097155))throw new L(J.D);if(N(a.node.mode))throw new L(J.P);if(!a.f.read)throw new L(J.h);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new L(J.W);b=a.f.read(a,b,c,d,f);g||(a.position+=b);return b}
function ka(a,b,c,d,f,g){if(0>d||0>f)throw new L(J.h);if(0===(a.flags&2097155))throw new L(J.D);if(N(a.node.mode))throw new L(J.P);if(!a.f.write)throw new L(J.h);a.flags&1024&&hc(a,0,2);var l="undefined"!==typeof f;if(!l)f=a.position;else if(!a.seekable)throw new L(J.W);b=a.f.write(a,b,c,d,f,g);l||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(r){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+r.message)}return b}
function ic(){L||(L=function(a,b){this.node=b;this.bb=function(a){this.g=a;for(var b in J)if(J[b]===a){this.code=b;break}};this.bb(a);this.message=pb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},L.prototype=Error(),L.prototype.constructor=L,[J.A].forEach(function(a){Gb[a]=new L(a);Gb[a].stack="<generic error, no stack>"}))}var jc;function fa(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function kc(a,b,c){a=m("/dev",a);var d=fa(!!b,!!c);lc||(lc=64);var f=lc++<<8|0;zb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,l=0;l<f;l++){try{var r=b()}catch(ja){throw new L(J.T);}if(void 0===r&&0===g)throw new L(J.na);if(null===r||void 0===r)break;g++;c[d+l]=r}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(u){throw new L(J.T);}f&&(a.node.timestamp=Date.now());
return g}});ac(a,d,f)}var lc,FS={},Sb,Zb,fc,xc={};
function Ic(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&sb(b)!==sb(Nb(f.node)))return-J.V;throw f;}D[c>>2]=d.dev;D[c+4>>2]=0;D[c+8>>2]=d.ino;D[c+12>>2]=d.mode;D[c+16>>2]=d.nlink;D[c+20>>2]=d.uid;D[c+24>>2]=d.gid;D[c+28>>2]=d.rdev;D[c+32>>2]=0;D[c+36>>2]=d.size;D[c+40>>2]=4096;D[c+44>>2]=d.blocks;D[c+48>>2]=d.atime.getTime()/1E3|0;D[c+52>>2]=0;D[c+56>>2]=d.mtime.getTime()/1E3|0;D[c+60>>2]=0;D[c+64>>2]=d.ctime.getTime()/1E3|0;D[c+68>>2]=0;D[c+72>>2]=d.ino;return 0}var V=0;
function W(){V+=4;return D[V-4>>2]}function X(){return H(W())}function Jc(){var a=Q[W()];if(!a)throw new L(J.D);return a}function Kc(a,b){V=b;return 0}var Lc=B;B+=16;var Mc,Y={};function Nc(a){if(0===a)return 0;a=H(a);if(!Y.hasOwnProperty(a))return 0;Nc.Y&&ea(Nc.Y);a=Y[a];var b=Wa(a)+1,c=Ta(b);c&&na(a,k,c,b);Nc.Y=c;return Nc.Y}var Z=B;B+=48;var Oc=ca(ba("GMT"),Ra);
function Pc(a){a/=1E3;if((x||z)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}e._usleep=Pc;function Qc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Rc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Sc=[31,29,31,30,31,30,31,31,30,31,30,31],Tc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Uc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Qc(a.getFullYear())?Sc:Tc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}ic();R=Array(4096);$b(M,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");zb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});ac("/dev/null",259);yb(1280,Cb);yb(1536,Db);ac("/dev/tty",1280);ac("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=A?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};kc("random",b);kc("urandom",b);U("/dev/shm");U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");
$b({o:function(){var a=Fb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=Q[+c];if(!b)throw new L(J.D);a={parent:null,o:{Ca:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
gb.unshift(function(){if(!e.noFSInit&&!jc){assert(!jc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");jc=!0;ic();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?kc("stdin",e.stdin):bc("/dev/tty","/dev/stdin");e.stdout?kc("stdout",null,e.stdout):bc("/dev/tty","/dev/stdout");e.stderr?kc("stderr",null,e.stderr):bc("/dev/tty1","/dev/stderr");var a=n("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=n("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=n("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});hb.push(function(){Lb=!1});ib.push(function(){jc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Q.length;a++){var b=Q[a];b&&la(b)}});gb.unshift(function(){});ib.push(function(){});if(A){var fs=require("fs"),Hb=require("path");P.cb()}var Vc,Wc;
Mc?(Wc=D[Lc>>2],Vc=D[Wc>>2]):(Mc=!0,Y.USER=Y.LOGNAME="web_user",Y.PATH="/",Y.PWD="/",Y.HOME="/home/web_user",Y.LANG="C.UTF-8",Y._=e.thisProgram,Vc=Aa(1024),Wc=Aa(256),D[Wc>>2]=Vc,D[Lc>>2]=Wc);var Xc=[],Yc=0,Zc;for(Zc in Y)if("string"===typeof Y[Zc]){var $c=Zc+"="+Y[Zc];Xc.push($c);Yc+=$c.length}if(1024<Yc)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var ad=0;ad<Xc.length;ad++){for(var bd=$c=Xc[ad],cd=Vc,dd=0;dd<bd.length;++dd)k[cd++>>0]=bd.charCodeAt(dd);k[cd>>0]=0;D[Wc+4*ad>>2]=Vc;Vc+=$c.length+1}D[Wc+4*Xc.length>>2]=0;C=Aa(4);$a=ab=Ea(B);bb=$a+db;cb=Ea(bb);D[C>>2]=cb;Ba=!0;function ba(a,b){var c=Array(Wa(a)+1);a=na(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=2304;e.wasmMaxTableSize=2304;e.La={};
e.Ma={abort:G,enlargeMemory:function(){Da()},getTotalMemory:function(){return E},abortOnCannotGrowMemory:Da,jsCall_i:function(a){return F[a]()},jsCall_ii:function(a,b){return F[a](b)},jsCall_iii:function(a,b,c){return F[a](b,c)},jsCall_iiii:function(a,b,c,d){return F[a](b,c,d)},jsCall_iiiii:function(a,b,c,d,f){return F[a](b,c,d,f)},jsCall_iiiiii:function(a,b,c,d,f,g){return F[a](b,c,d,f,g)},jsCall_iiiiiii:function(a,b,c,d,f,g,l){return F[a](b,c,d,f,g,l)},jsCall_iiiij:function(a,b,c,d,f){return F[a](b,
c,d,f)},jsCall_iij:function(a,b,c){return F[a](b,c)},jsCall_iiji:function(a,b,c,d){return F[a](b,c,d)},jsCall_iijii:function(a,b,c,d,f){return F[a](b,c,d,f)},jsCall_vi:function(a,b){F[a](b)},jsCall_vii:function(a,b,c){F[a](b,c)},jsCall_viii:function(a,b,c,d){F[a](b,c,d)},jsCall_viiii:function(a,b,c,d,f){F[a](b,c,d,f)},jsCall_viiiij:function(a,b,c,d,f,g){F[a](b,c,d,f,g)},jsCall_viji:function(a,b,c,d){F[a](b,c,d)},___assert_fail:function(a,b,c,d){G("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",
c,d?H(d):"unknown function"])},___setErrNo:qb,___syscall10:function(a,b){V=b;try{var c=X();ta(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof L||G(d),-d.g}},___syscall118:function(a,b){V=b;try{return Jc(),0}catch(c){return"undefined"!==typeof FS&&c instanceof L||G(c),-c.g}},___syscall140:function(a,b){V=b;try{var c=Jc();W();var d=W(),f=W(),g=W();hc(c,d,g);D[f>>2]=c.position;c.ja&&0===d&&0===g&&(c.ja=null);return 0}catch(l){return"undefined"!==typeof FS&&l instanceof L||G(l),-l.g}},
___syscall15:function(a,b){V=b;try{var c=X(),d=W();ia(c,d);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall183:function(a,b){V=b;try{var c=W(),d=W();if(0===d)return-J.h;if(d<Wa("/")+1)return-J.Ga;na("/",q,c,d);return c}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall192:function(a,b){V=b;try{var c=W(),d=W(),f=W(),g=W(),l=W(),r=W();r<<=12;a=!1;if(-1===l){var y=ed(16384,d);if(!y)return-J.pa;fd(y,0,d);a=!0}else{var w=Q[l];if(!w)return-J.D;
b=q;if(1===(w.flags&2097155))throw new L(J.N);if(!w.f.$)throw new L(J.U);var u=w.f.$(w,b,c,d,r,f,g);y=u.$a;a=u.ga}xc[y]={Ya:y,Xa:d,ga:a,fd:l,flags:g};return y}catch(K){return"undefined"!==typeof FS&&K instanceof L||G(K),-K.g}},___syscall194:function(a,b){V=b;try{var c=W();assert(0===W());var d=W(),f=W();0<=d?assert(0===f):assert(-1===f);var g=Q[c];if(!g)throw new L(J.D);if(0===(g.flags&2097155))throw new L(J.h);ec(g.node,d);return 0}catch(l){return"undefined"!==typeof FS&&l instanceof L||G(l),-l.g}},
___syscall195:function(a,b){V=b;try{var c=X(),d=W();return Ic(qa,c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall196:function(a,b){V=b;try{var c=X(),d=W();return Ic(cc,c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall197:function(a,b){V=b;try{var c=Jc(),d=W();return Ic(qa,c.path,d)}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall20:function(a,b){V=b;return 42},___syscall201:function(){return Kc.apply(null,
arguments)},___syscall207:function(a,b){V=b;try{var c=W();W();W();var d=Q[c];if(!d)throw new L(J.D);dc(d.node);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall212:function(a,b){V=b;try{var c=X();W();W();dc(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof L||G(d),-d.g}},___syscall221:function(a,b){V=b;try{var c=Jc();switch(W()){case 0:var d=W();return 0>d?-J.h:n(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=
W(),c.flags|=d,0;case 12:case 12:return d=W(),Ka[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-J.h;case 9:return qb(J.h),-1;default:return-J.h}}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall3:function(a,b){V=b;try{var c=Jc(),d=W(),f=W();return ra(c,k,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof L||G(g),-g.g}},___syscall33:function(a,b){V=b;try{var c=X();var d=W();if(d&-8)var f=-J.h;else{var g=T(c,{I:!0}).node;a="";d&4&&(a+=
"r");d&2&&(a+="w");d&1&&(a+="x");f=a&&Rb(g,a)?-J.N:0}return f}catch(l){return"undefined"!==typeof FS&&l instanceof L||G(l),-l.g}},___syscall39:function(a,b){V=b;try{var c=X(),d=W();a=c;a=sb(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));U(a,d);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof L||G(f),-f.g}},___syscall4:function(a,b){V=b;try{var c=Jc(),d=W(),f=W();return ka(c,k,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof L||G(g),-g.g}},___syscall40:function(a,b){V=b;try{var c=
X(),d=T(c,{parent:!0}).node,f=ub(c),g=O(d,f),l=Wb(d,f,!0);if(l)throw new L(l);if(!d.c.rmdir)throw new L(J.B);if(g.K)throw new L(J.O);try{S.willDeletePath&&S.willDeletePath(c)}catch(r){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+r.message)}d.c.rmdir(d,f);Qb(g);try{if(S.onDeletePath)S.onDeletePath(c)}catch(r){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+r.message)}return 0}catch(r){return"undefined"!==typeof FS&&r instanceof L||
G(r),-r.g}},___syscall5:function(a,b){V=b;try{var c=X(),d=W(),f=W();return n(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof L||G(g),-g.g}},___syscall6:function(a,b){V=b;try{var c=Jc();la(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof L||G(d),-d.g}},___syscall85:function(a,b){V=b;try{var c=X(),d=W();var f=W();if(0>=f)var g=-J.h;else{var l=Mb(c),r=Math.min(f,Wa(l)),y=k[d+r];na(l,q,d,f+1);k[d+r]=y;g=r}return g}catch(w){return"undefined"!==typeof FS&&w instanceof L||
G(w),-w.g}},___syscall91:function(a,b){V=b;try{var c=W(),d=W(),f=xc[c];if(!f)return 0;if(d===f.Xa){var g=Q[f.fd],l=f.flags,r=new Uint8Array(q.subarray(c,c+d));g&&g.f.aa&&g.f.aa(g,r,0,d,l);xc[c]=null;f.ga&&ea(f.Ya)}return 0}catch(y){return"undefined"!==typeof FS&&y instanceof L||G(y),-y.g}},___syscall94:function(a,b){V=b;try{var c=W(),d=W(),f=Q[c];if(!f)throw new L(J.D);ia(f.node,d);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof L||G(g),-g.g}},_emscripten_memcpy_big:function(a,b,c){q.set(q.subarray(b,
b+c),a);return a},_getenv:Nc,_gettimeofday:function(a){var b=Date.now();D[a>>2]=b/1E3|0;D[a+4>>2]=b%1E3*1E3|0;return 0},_gmtime:function(a){a=new Date(1E3*D[a>>2]);D[Z>>2]=a.getUTCSeconds();D[Z+4>>2]=a.getUTCMinutes();D[Z+8>>2]=a.getUTCHours();D[Z+12>>2]=a.getUTCDate();D[Z+16>>2]=a.getUTCMonth();D[Z+20>>2]=a.getUTCFullYear()-1900;D[Z+24>>2]=a.getUTCDay();D[Z+36>>2]=0;D[Z+32>>2]=0;D[Z+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;D[Z+40>>2]=Oc;return Z},_llvm_trap:function(){G("trap!")},
_nanosleep:function(a,b){var c=D[a>>2];a=D[a+4>>2];0!==b&&(D[b>>2]=0,D[b+4>>2]=0);return Pc(1E6*c+a/1E3)},_sqlite3AlterBeginAddColumn:function(){e.printErr("missing function: sqlite3AlterBeginAddColumn");G(-1)},_sqlite3AlterFinishAddColumn:function(){e.printErr("missing function: sqlite3AlterFinishAddColumn");G(-1)},_sqlite3AlterRenameTable:function(){e.printErr("missing function: sqlite3AlterRenameTable");G(-1)},_sqlite3Analyze:function(){e.printErr("missing function: sqlite3Analyze");G(-1)},_sqlite3Attach:function(){e.printErr("missing function: sqlite3Attach");
G(-1)},_sqlite3CreateView:function(){e.printErr("missing function: sqlite3CreateView");G(-1)},_sqlite3Detach:function(){e.printErr("missing function: sqlite3Detach");G(-1)},_sqlite3Pragma:function(){e.printErr("missing function: sqlite3Pragma");G(-1)},_sqlite3Reindex:function(){e.printErr("missing function: sqlite3Reindex");G(-1)},_sqlite3Vacuum:function(){e.printErr("missing function: sqlite3Vacuum");G(-1)},_sqlite3VtabArgExtend:function(){e.printErr("missing function: sqlite3VtabArgExtend");G(-1)},
_sqlite3VtabArgInit:function(){e.printErr("missing function: sqlite3VtabArgInit");G(-1)},_sqlite3VtabBeginParse:function(){e.printErr("missing function: sqlite3VtabBeginParse");G(-1)},_sqlite3VtabFinishParse:function(){e.printErr("missing function: sqlite3VtabFinishParse");G(-1)},_strftime:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function l(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=
c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function r(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function y(a){a=Uc(new Date(a.m+1900,0,1),a.ea);var b=r(new Date(a.getFullYear()+
1,0,4));return 0>=l(r(new Date(a.getFullYear(),0,4)),a)?0>=l(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var w=D[d+40>>2];d={gb:D[d>>2],fb:D[d+4>>2],da:D[d+8>>2],J:D[d+12>>2],G:D[d+16>>2],m:D[d+20>>2],Da:D[d+24>>2],ea:D[d+28>>2],Kd:D[d+32>>2],eb:D[d+36>>2],hb:w?H(w):""};c=H(c);w={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var u in w)c=c.replace(new RegExp(u,"g"),w[u]);var K=
"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ja="January February March April May June July August September October November December".split(" ");w={"%a":function(a){return K[a.Da].substring(0,3)},"%A":function(a){return K[a.Da]},"%b":function(a){return ja[a.G].substring(0,3)},"%B":function(a){return ja[a.G]},"%C":function(a){return g((a.m+1900)/100|0,2)},"%d":function(a){return g(a.J,2)},"%e":function(a){return f(a.J,2," ")},"%g":function(a){return y(a).toString().substring(2)},
"%G":function(a){return y(a)},"%H":function(a){return g(a.da,2)},"%I":function(a){a=a.da;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.J+Rc(Qc(a.m+1900)?Sc:Tc,a.G-1),3)},"%m":function(a){return g(a.G+1,2)},"%M":function(a){return g(a.fb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.da&&12>a.da?"AM":"PM"},"%S":function(a){return g(a.gb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.m+1900,a.G+1,a.J,0,0,0,0)).getDay()||7},"%U":function(a){var b=
new Date(a.m+1900,0,1),c=0===b.getDay()?b:Uc(b,7-b.getDay());a=new Date(a.m+1900,a.G,a.J);return 0>l(c,a)?g(Math.ceil((31-c.getDate()+(Rc(Qc(a.getFullYear())?Sc:Tc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%V":function(a){var b=r(new Date(a.m+1900,0,4)),c=r(new Date(a.m+1901,0,4)),d=Uc(new Date(a.m+1900,0,1),a.ea);return 0>l(d,b)?"53":0>=l(c,d)?"01":g(Math.ceil((b.getFullYear()<a.m+1900?a.ea+32-b.getDate():a.ea+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.m+1900,a.G+
1,a.J,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.m,0,1),c=1===b.getDay()?b:Uc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.m+1900,a.G,a.J);return 0>l(c,a)?g(Math.ceil((31-c.getDate()+(Rc(Qc(a.getFullYear())?Sc:Tc,a.getMonth()-1)-31)+a.getDate())/7),2):0===l(c,b)?"01":"00"},"%y":function(a){return(a.m+1900).toString().substring(2)},"%Y":function(a){return a.m+1900},"%z":function(a){a=a.eb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.hb},
"%%":function(){return"%"}};for(u in w)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),w[u](d)));u=ba(c,!1);if(u.length>b)return 0;k.set(u,a);return u.length-1},_sysconf:function(a){switch(a){case 30:return 16384;case 85:return q.length/16384;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}qb(J.h);return-1},
_time:function(a){var b=Date.now()/1E3|0;a&&(D[a>>2]=b);return b},_utimes:function(a,b){if(b){var c=1E3*D[b+8>>2];c+=D[b+12>>2]/1E3}else c=Date.now();a=H(a);try{b=c;var d=T(a,{I:!0}).node;d.c.l(d,{timestamp:Math.max(b,c)});return 0}catch(f){a=f;if(!(a instanceof L)){a+=" : ";a:{d=Error();if(!d.stack){try{throw Error(0);}catch(g){d=g}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}e.extraStackTrace&&(d+="\n"+e.extraStackTrace());d=Xa(d);throw a+d;}qb(a.g);return-1}},DYNAMICTOP_PTR:C,
STACKTOP:ab};var gd=e.asm(e.La,e.Ma,buffer);e.asm=gd;e._RegisterExtensionFunctions=function(){return e.asm._RegisterExtensionFunctions.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};
var ea=e._free=function(){return e.asm._free.apply(null,arguments)},Ta=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},ed=e._memalign=function(){return e.asm._memalign.apply(null,arguments)},fd=e._memset=function(){return e.asm._memset.apply(null,arguments)};e._sqlite3_bind_blob=function(){return e.asm._sqlite3_bind_blob.apply(null,arguments)};e._sqlite3_bind_double=function(){return e.asm._sqlite3_bind_double.apply(null,arguments)};
e._sqlite3_bind_int=function(){return e.asm._sqlite3_bind_int.apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return e.asm._sqlite3_bind_parameter_index.apply(null,arguments)};e._sqlite3_bind_text=function(){return e.asm._sqlite3_bind_text.apply(null,arguments)};e._sqlite3_changes=function(){return e.asm._sqlite3_changes.apply(null,arguments)};e._sqlite3_clear_bindings=function(){return e.asm._sqlite3_clear_bindings.apply(null,arguments)};
e._sqlite3_close_v2=function(){return e.asm._sqlite3_close_v2.apply(null,arguments)};e._sqlite3_column_blob=function(){return e.asm._sqlite3_column_blob.apply(null,arguments)};e._sqlite3_column_bytes=function(){return e.asm._sqlite3_column_bytes.apply(null,arguments)};e._sqlite3_column_double=function(){return e.asm._sqlite3_column_double.apply(null,arguments)};e._sqlite3_column_name=function(){return e.asm._sqlite3_column_name.apply(null,arguments)};
e._sqlite3_column_text=function(){return e.asm._sqlite3_column_text.apply(null,arguments)};e._sqlite3_column_type=function(){return e.asm._sqlite3_column_type.apply(null,arguments)};e._sqlite3_create_function_v2=function(){return e.asm._sqlite3_create_function_v2.apply(null,arguments)};e._sqlite3_data_count=function(){return e.asm._sqlite3_data_count.apply(null,arguments)};e._sqlite3_errmsg=function(){return e.asm._sqlite3_errmsg.apply(null,arguments)};
e._sqlite3_exec=function(){return e.asm._sqlite3_exec.apply(null,arguments)};e._sqlite3_finalize=function(){return e.asm._sqlite3_finalize.apply(null,arguments)};e._sqlite3_free=function(){return e.asm._sqlite3_free.apply(null,arguments)};e._sqlite3_open=function(){return e.asm._sqlite3_open.apply(null,arguments)};e._sqlite3_prepare_v2=function(){return e.asm._sqlite3_prepare_v2.apply(null,arguments)};e._sqlite3_reset=function(){return e.asm._sqlite3_reset.apply(null,arguments)};
e._sqlite3_result_double=function(){return e.asm._sqlite3_result_double.apply(null,arguments)};e._sqlite3_result_null=function(){return e.asm._sqlite3_result_null.apply(null,arguments)};e._sqlite3_result_text=function(){return e.asm._sqlite3_result_text.apply(null,arguments)};e._sqlite3_step=function(){return e.asm._sqlite3_step.apply(null,arguments)};e._sqlite3_value_blob=function(){return e.asm._sqlite3_value_blob.apply(null,arguments)};
e._sqlite3_value_bytes=function(){return e.asm._sqlite3_value_bytes.apply(null,arguments)};e._sqlite3_value_double=function(){return e.asm._sqlite3_value_double.apply(null,arguments)};e._sqlite3_value_int=function(){return e.asm._sqlite3_value_int.apply(null,arguments)};e._sqlite3_value_text=function(){return e.asm._sqlite3_value_text.apply(null,arguments)};e._sqlite3_value_type=function(){return e.asm._sqlite3_value_type.apply(null,arguments)};
var aa=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)},pa=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},ma=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.asm=gd;
e.cwrap=function(a,b,c){c=c||[];var d=Ha(a),f=c.every(function(a){return"number"===a});return"string"!==b&&f?d:function(){var d=c,f=arguments,r=Ha(a),y=[],w=0;if(f)for(var u=0;u<f.length;u++){var K=Ja[d[u]];K?(0===w&&(w=ma()),y[u]=K(f[u])):y[u]=f[u]}d=r.apply(null,y);"string"===b&&(d=H(d));0!==w&&pa(w);return d}};e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};
function za(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}za.prototype=Error();za.prototype.constructor=za;nb=function hd(){e.calledRun||id();e.calledRun||(nb=hd)};
function id(){function a(){if(!e.calledRun&&(e.calledRun=!0,!Ga)){kb||(kb=!0,eb(gb));eb(hb);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();jb.unshift(a)}eb(jb)}}if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)lb();eb(fb);0<I||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=id;e.exit=function(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(Ga=!0,ab=void 0,eb(ib),e.onExit))e.onExit(a);A&&process.exit(a);e.quit(a,new za(a))}};function G(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";Ga=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=G;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;id();
this.SQL=e;


  return SQL;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = SQL;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return SQL; });
else if (typeof exports === 'object')
  exports["SQL"] = SQL;
