var SQL = function(SQL) {
  SQL = SQL || {};

var e;e||(e=typeof SQL !== 'undefined' ? SQL : {});e.ENVIRONMENT="WEB";var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var l=!1,m=!1,p=!1,ba=!1;
if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)l=!0;else if("WORKER"===e.ENVIRONMENT)m=!0;else if("NODE"===e.ENVIRONMENT)p=!0;else if("SHELL"===e.ENVIRONMENT)ba=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else l="object"===typeof window,m="function"===typeof importScripts,p="object"===typeof process&&"function"===typeof require&&!l&&!m,ba=!l&&!p&&!m;
if(p){var ca,da;e.read=function(a,b){ca||(ca=require("fs"));da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ea))throw a;});process.on("unhandledRejection",function(){process.exit(1)});e.inspect=
function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(l||m)e.read=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},m&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),e.setWindowTitle=function(a){document.title=a};
e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=void 0;function fa(a){assert(!ha);var b=q;q=q+a+15&-16;return b}function ia(a){assert(r);var b=u[r>>2];a=b+a+15&-16;u[r>>2]=a;if(a=a>=w)ja(),a=!0;return a?(u[r>>2]=b,0):b}
function ka(a){var b;b||(b=16);return Math.ceil(a/b)*b}var y=Array(64);function la(a){for(var b=0;64>b;b++)if(!y[b])return y[b]=a,1+b;throw"Finished up all reserved function pointers. Use a higher value for RESERVED_FUNCTION_POINTERS.";}var ma=0;function assert(a,b){a||z("Assertion failed: "+b)}function na(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
var ta={stackSave:function(){pa()},stackRestore:function(){qa()},arrayToC:function(a){var b=ra(a.length);A.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=ra(c);sa(a,B,b,c)}return b}},ua={string:ta.stringToC,array:ta.arrayToC};
function va(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":A[a>>0]=0;break;case "i8":A[a>>0]=0;break;case "i16":wa[a>>1]=0;break;case "i32":u[a>>2]=0;break;case "i64":tempI64=[0,(tempDouble=0,1<=+xa(tempDouble)?0<tempDouble?(ya(+za(tempDouble/4294967296),4294967295)|0)>>>0:~~+Aa((tempDouble-+(~~tempDouble>>>0))/4294967296)>>>0:0)];u[a>>2]=tempI64[0];u[a+4>>2]=tempI64[1];break;case "float":Ba[a>>2]=0;break;case "double":Ca[a>>3]=0;break;default:z("invalid type for setValue: "+
b)}}function C(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return A[a>>0];case "i8":return A[a>>0];case "i16":return wa[a>>1];case "i32":return u[a>>2];case "i64":return u[a>>2];case "float":return Ba[a>>2];case "double":return Ca[a>>3];default:z("invalid type for getValue: "+b)}return null}
function Da(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=4==b?f:["function"===typeof Ea?Ea:fa,ra,fa,ia][void 0===b?2:b](Math.max(d,1));if(c){var f=b;assert(0==(b&3));for(a=b+(d&-4);f<a;f+=4)u[f>>2]=0;for(a=b+d;f<a;)A[f++>>0]=0;return b}a.subarray||a.slice?B.set(a,b):B.set(new Uint8Array(a),b);return b}
function D(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=B[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,B.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return Fa(B,a)}var Ga="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Fa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Ga)return Ga.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|n;else{var x=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|n<<6|x}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function sa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ia(a){return a.replace(/__Z[\w\d_]+/g,function(a){return a===a?a:a+" ["+a+"]"})}var buffer,A,B,wa,u,Ba,Ca;
function Ja(){e.HEAP8=A=new Int8Array(buffer);e.HEAP16=wa=new Int16Array(buffer);e.HEAP32=u=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=Ba=new Float32Array(buffer);e.HEAPF64=Ca=new Float64Array(buffer)}var Ka,q,ha,La,Ma,Na,Oa,r;Ka=q=La=Ma=Na=Oa=r=0;ha=!1;
function ja(){z("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+w+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Pa=e.TOTAL_STACK||5242880,w=e.TOTAL_MEMORY||16777216;w<Pa&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+w+"! (TOTAL_STACK="+Pa+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:w/65536,maximum:w/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(w),e.buffer=buffer);Ja();u[0]=1668509029;wa[1]=25459;if(115!==B[2]||99!==B[3])throw"Runtime error: expected the system to be little-endian!";
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Id;"number"===typeof c?void 0===b.ia?e.dynCall_v(c):e.dynCall_vi(c,b.ia):c(void 0===b.ia?null:b.ia)}}}var Ra=[],Sa=[],Ta=[],Ua=[],Va=[],Wa=!1;function Xa(){var a=e.preRun.shift();Ra.unshift(a)}var xa=Math.abs,Aa=Math.ceil,za=Math.floor,ya=Math.min,E=0,Ya=null,Za=null;e.preloadedImages={};e.preloadedAudios={};
function $a(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(t){z(t)}}function b(){return e.wasmBinary||!l&&!m||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=n.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Ja()}e.asm=n;e.usingWasm=!0;E--;e.monitorRunDependencies&&e.monitorRunDependencies(E);0==E&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za&&(a=Za,Za=null,a()))}
function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+a);z(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;E++;e.monitorRunDependencies&&e.monitorRunDependencies(E);
if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(kb){return e.printErr("Module.instantiateWasm callback failed with error: "+kb),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||$a(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="sql-optimized-wasm-raw.wast",
f="sql-optimized-wasm-raw.wasm",g="sql-optimized-wasm-raw.temp.asm.js";"function"===typeof e.locateFile&&($a(d)||(d=e.locateFile(d)),$a(f)||(f=e.locateFile(f)),$a(g)||(g=e.locateFile(g)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},parent:e},n=null;e.asmPreload=e.asm;var x=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===v)var b=x(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=
-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(Ib){b=null;break a}b=void 0}return b};var v="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);
b.tableBase||(b.tableBase=0);(b=c(b))||z("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();Ka=1024;q=Ka+28832;Sa.push();e.STATIC_BASE=Ka;e.STATIC_BUMP=28832;q+=16;
var F={B:1,A:2,ad:3,Wb:4,T:5,ra:6,pb:7,uc:8,D:9,Db:10,na:11,md:11,pa:12,N:13,Pb:14,Gc:15,O:16,oa:17,nd:18,U:19,V:20,P:21,h:22,pc:23,Fa:24,Lc:25,jd:26,Qb:27,Cc:28,W:29,Xc:30,ic:31,Rc:32,Mb:33,Ga:34,yc:42,Tb:43,Eb:44,Zb:45,$b:46,ac:47,hc:48,kd:49,sc:50,Yb:51,Jb:35,vc:37,vb:52,yb:53,od:54,qc:55,zb:56,Ab:57,Kb:35,Bb:59,Ec:60,tc:61,ed:62,Dc:63,zc:64,Ac:65,Wc:66,wc:67,sb:68,bd:69,Fb:70,Sc:71,kc:72,Nb:73,xb:74,Mc:76,wb:77,Vc:78,bc:79,cc:80,fc:81,ec:82,dc:83,Fc:38,qa:39,lc:36,fa:40,Nc:95,Qc:96,Ib:104,rc:105,
tb:97,Uc:91,Jc:88,Bc:92,Zc:108,Hb:111,qb:98,Gb:103,oc:101,mc:100,gd:110,Rb:112,Sb:113,Vb:115,ub:114,Lb:89,jc:90,Tc:93,$c:94,rb:99,nc:102,Xb:106,Hc:107,hd:109,ld:87,Ob:122,cd:116,Kc:95,xc:123,Ub:84,Oc:75,Cb:125,Ic:131,Pc:130,dd:86},ab={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function bb(a){e.___errno_location&&(u[e.___errno_location()>>2]=a);return a}
function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function db(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function gb(){var a=Array.prototype.slice.call(arguments,0);return db(a.join("/"))}function G(a,b){return db(a+"/"+b)}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],output:[],M:b};lb(a,mb)}
var mb={open:function(a){var b=ib[a.node.rdev];if(!b)throw new H(F.U);a.tty=b;a.seekable=!1},close:function(a){a.tty.M.flush(a.tty)},flush:function(a){a.tty.M.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.M.Ba)throw new H(F.ra);for(var f=0,g=0;g<d;g++){try{var h=a.tty.M.Ba(a.tty)}catch(n){throw new H(F.T);}if(void 0===h&&0===f)throw new H(F.na);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.M.la)throw new H(F.ra);
for(var f=0;f<d;f++)try{a.tty.M.la(a.tty,b[c+f])}catch(g){throw new H(F.T);}d&&(a.node.timestamp=Date.now());return f}},ob={Ba:function(a){if(!a.input.length){var b=null;if(p){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},la:function(a,b){null===b||10===b?(e.print(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(Fa(a.output,0)),a.output=[])}},pb={la:function(a,b){null===b||10===b?(e.printErr(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(Fa(a.output,0)),a.output=[])}},I={v:null,o:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(F.B);I.v||(I.v={dir:{node:{u:I.c.u,l:I.c.l,lookup:I.c.lookup,R:I.c.R,rename:I.c.rename,unlink:I.c.unlink,rmdir:I.c.rmdir,readdir:I.c.readdir,symlink:I.c.symlink},stream:{F:I.f.F}},file:{node:{u:I.c.u,l:I.c.l},stream:{F:I.f.F,read:I.f.read,write:I.f.write,sa:I.f.sa,$:I.f.$,aa:I.f.aa}},link:{node:{u:I.c.u,
l:I.c.l,readlink:I.c.readlink},stream:{}},va:{node:{u:I.c.u,l:I.c.l},stream:qb}});c=rb(a,b,c,d);K(c.mode)?(c.c=I.v.dir.node,c.f=I.v.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=I.v.file.node,c.f=I.v.file.stream,c.i=0,c.b=null):40960===(c.mode&61440)?(c.c=I.v.link.node,c.f=I.v.link.stream):8192===(c.mode&61440)&&(c.c=I.v.va.node,c.f=I.v.va.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ua:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.i;++c)b.push(a.b[c]);return b}return a.b},Jd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.i):new Uint8Array(a.b):new Uint8Array},wa:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=I.Ua(a),a.i=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.i&&a.b.set(c.subarray(0,a.i),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},ab:function(a,b){if(a.i!=b)if(0==b)a.b=null,a.i=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.i)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.i=b}},c:{u:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.i:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.H=4096;b.blocks=Math.ceil(b.size/b.H);return b},
l:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.ab(a,b.size)},lookup:function(){throw sb[F.A];},R:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(K(a.mode)){try{var d=L(b,c)}catch(g){}if(d)for(var f in d.b)throw new H(F.qa);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=L(a,b),d;for(d in c.b)throw new H(F.qa);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(F.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.i)return 0;a=Math.min(a.node.i-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.i=d;if(0===a.i&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.i=d;if(f+d<=a.i)return a.b.set(b.subarray(c,c+d),f),d}I.wa(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.i=Math.max(a.i,f+d);return d},F:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.i);if(0>b)throw new H(F.h);return b},sa:function(a,b,c){I.wa(a.node,b+c);a.node.i=Math.max(a.node.i,
b+c)},$:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new H(F.U);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.i)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=Ea(d);if(!d)throw new H(F.pa);b.set(c,d)}else a=!1,d=c.byteOffset;return{$a:d,ga:a}},aa:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new H(F.U);if(f&2)return 0;I.f.write(a,b,0,d,c,!1);return 0}}},M={Z:!1,cb:function(){M.Z=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);M.ya={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ua:function(a){return Buffer.Y?Buffer.from(a):new Buffer(a)},o:function(a){assert(p);return M.createNode(null,"/",M.Aa(a.ka.root),0)},createNode:function(a,b,c){if(!K(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new H(F.h);a=rb(a,b,c);a.c=M.c;a.f=M.f;return a},Aa:function(a){try{var b=fs.lstatSync(a);M.Z&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new H(F[c.code]);}return b.mode},s:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.o.ka.root);b.reverse();return gb.apply(null,b)},Ta:function(a){a&=-2656257;var b=0,c;for(c in M.ya)a&c&&(b|=M.ya[c],a^=c);if(a)throw new H(F.h);return b},c:{u:function(a){a=M.s(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}M.Z&&!b.H&&(b.H=4096);M.Z&&!b.blocks&&(b.blocks=(b.size+b.H-1)/b.H|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,H:b.H,blocks:b.blocks}},l:function(a,b){var c=M.s(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new H(F[d.code]);}},lookup:function(a,b){var c=G(M.s(a),b);c=M.Aa(c);return M.createNode(a,b,c)},R:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.s(a);try{K(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new H(F[f.code]);}return a},rename:function(a,b,c){a=M.s(a);b=G(M.s(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new H(F[d.code]);}},unlink:function(a,b){a=G(M.s(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}},rmdir:function(a,b){a=G(M.s(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}},readdir:function(a){a=M.s(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new H(F[b.code]);}},symlink:function(a,
b,c){a=G(M.s(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new H(F[d.code]);}},readlink:function(a){var b=M.s(a);try{return b=fs.readlinkSync(b),b=tb.relative(tb.resolve(a.o.ka.root),b)}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}}},f:{open:function(a){var b=M.s(a.node);try{32768===(a.node.mode&61440)&&(a.S=fs.openSync(b,M.Ta(a.flags)))}catch(c){if(!c.code)throw c;throw new H(F[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.S&&fs.closeSync(a.S)}catch(b){if(!b.code)throw b;
throw new H(F[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.S,M.ua(b.buffer),c,d,f)}catch(g){throw new H(F[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.S,M.ua(b.buffer),c,d,f)}catch(g){throw new H(F[g.code]);}},F:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.S).size}catch(d){throw new H(F[d.code]);}if(0>b)throw new H(F.h);return b}}};q+=16;q+=16;q+=16;
var ub=null,vb={},N=[],wb=1,O=null,xb=!0,P={},H=null,sb={};
function Q(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={za:!0,ma:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ma)throw new H(F.fa);a=cb(a.split("/").filter(function(a){return!!a}),!1);var f=ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=L(f,a[d]);c=G(c,a[d]);f.K&&(!g||g&&b.za)&&(f=f.K.root);if(!g||b.I)for(g=0;40960===(f.mode&61440);)if(f=yb(c),c=hb(eb(c),f),f=Q(c,{ma:b.ma}).node,40<g++)throw new H(F.fa);}return{path:c,node:f}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.o.Ca,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function Bb(a){var b=Ab(a.parent.id,a.name);a.L=O[b];O[b]=a}function Cb(a){var b=Ab(a.parent.id,a.name);if(O[b]===a)O[b]=a.L;else for(b=O[b];b;){if(b.L===a){b.L=a.L;break}b=b.L}}
function L(a,b){var c;if(c=(c=Db(a,"x"))?c:a.c.lookup?0:F.N)throw new H(c,a);for(c=O[Ab(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function rb(a,b,c,d){Eb||(Eb=function(a,b,c,d){a||(a=this);this.parent=a;this.o=a.o;this.K=null;this.id=wb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Eb.prototype={},Object.defineProperties(Eb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Eb(a,b,c,d);Bb(a);return a}function K(a){return 16384===(a&61440)}
var Fb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Db(a,b){if(xb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return F.N}else return F.N;return 0}function Hb(a,b){try{return L(a,b),F.oa}catch(c){}return Db(a,"wx")}
function Jb(a,b,c){try{var d=L(a,b)}catch(f){return f.g}if(a=Db(a,"wx"))return a;if(c){if(!K(d.mode))return F.V;if(d===d.parent||"/"===zb(d))return F.O}else if(K(d.mode))return F.P;return 0}function Kb(a){var b=4096;for(a=a||0;a<=b;a++)if(!N[a])return a;throw new H(F.Fa);}
function Lb(a,b){Mb||(Mb=function(){},Mb.prototype={},Object.defineProperties(Mb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Mb,d;for(d in a)c[d]=a[d];a=c;b=Kb(b);a.fd=b;return N[b]=a}var qb={open:function(a){a.f=vb[a.node.rdev].f;a.f.open&&a.f.open(a)},F:function(){throw new H(F.W);}};function lb(a,b){vb[a]={f:b}}
function Nb(a,b){var c="/"===b,d=!b;if(c&&ub)throw new H(F.O);if(!c&&!d){var f=Q(b,{za:!1});b=f.path;f=f.node;if(f.K)throw new H(F.O);if(!K(f.mode))throw new H(F.V);}b={type:a,ka:{},Ca:b,Za:[]};a=a.o(b);a.o=b;b.root=a;c?ub=a:f&&(f.K=b,f.o&&f.o.Za.push(b))}function Ob(a,b,c){var d=Q(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new H(F.h);var f=Hb(d,a);if(f)throw new H(f);if(!d.c.R)throw new H(F.B);return d.c.R(d,a,b,c)}function R(a,b){Ob(a,(void 0!==b?b:511)&1023|16384,0)}
function Pb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ob(a,b|8192,c)}function Qb(a,b){if(!hb(a))throw new H(F.A);var c=Q(b,{parent:!0}).node;if(!c)throw new H(F.A);b=fb(b);var d=Hb(c,b);if(d)throw new H(d);if(!c.c.symlink)throw new H(F.B);c.c.symlink(c,b,a)}
function Rb(a){var b=Q(a,{parent:!0}).node,c=fb(a),d=L(b,c),f=Jb(b,c,!1);if(f)throw new H(f);if(!b.c.unlink)throw new H(F.B);if(d.K)throw new H(F.O);try{P.willDeletePath&&P.willDeletePath(a)}catch(g){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.c.unlink(b,c);Cb(d);try{if(P.onDeletePath)P.onDeletePath(a)}catch(g){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}}
function yb(a){a=Q(a).node;if(!a)throw new H(F.A);if(!a.c.readlink)throw new H(F.h);return hb(zb(a.parent),a.c.readlink(a))}function Sb(a,b){a=Q(a,{I:!b}).node;if(!a)throw new H(F.A);if(!a.c.u)throw new H(F.B);return a.c.u(a)}function Tb(a){return Sb(a,!0)}function Ub(a,b){var c;"string"===typeof a?c=Q(a,{I:!0}).node:c=a;if(!c.c.l)throw new H(F.B);c.c.l(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Vb(a){var b;"string"===typeof a?b=Q(a,{I:!0}).node:b=a;if(!b.c.l)throw new H(F.B);b.c.l(b,{timestamp:Date.now()})}function Wb(a,b){if(0>b)throw new H(F.h);var c;"string"===typeof a?c=Q(a,{I:!0}).node:c=a;if(!c.c.l)throw new H(F.B);if(K(c.mode))throw new H(F.P);if(32768!==(c.mode&61440))throw new H(F.h);if(a=Db(c,"w"))throw new H(a);c.c.l(c,{size:b,timestamp:Date.now()})}
function S(a,b,c,d){if(""===a)throw new H(F.A);if("string"===typeof b){var f=Fb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=db(a);try{g=Q(a,{I:!(b&131072)}).node}catch(h){}}f=!1;if(b&64)if(g){if(b&128)throw new H(F.oa);}else g=Ob(a,c,0),f=!0;if(!g)throw new H(F.A);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!K(g.mode))throw new H(F.V);if(!f&&(c=g?40960===(g.mode&61440)?F.fa:K(g.mode)&&
("r"!==Gb(b)||b&512)?F.P:Db(g,Gb(b)):F.A))throw new H(c);b&512&&Wb(g,0);b&=-641;d=Lb({node:g,path:zb(g),flags:b,seekable:!0,position:0,f:g.f,ib:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(Xb||(Xb={}),a in Xb||(Xb[a]=1,e.printErr("read file: "+a)));try{P.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),P.onOpenFile(a,g))}catch(h){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}
function Yb(a){a.ja&&(a.ja=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{N[a.fd]=null}}function Zb(a,b,c){if(!a.seekable||!a.f.F)throw new H(F.W);a.position=a.f.F(a,b,c);a.ib=[]}function $b(a,b,c,d,f){if(0>d||0>f)throw new H(F.h);if(1===(a.flags&2097155))throw new H(F.D);if(K(a.node.mode))throw new H(F.P);if(!a.f.read)throw new H(F.h);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new H(F.W);b=a.f.read(a,b,c,d,f);g||(a.position+=b);return b}
function ac(a,b,c,d,f,g){if(0>d||0>f)throw new H(F.h);if(0===(a.flags&2097155))throw new H(F.D);if(K(a.node.mode))throw new H(F.P);if(!a.f.write)throw new H(F.h);a.flags&1024&&Zb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new H(F.W);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&P.onWriteToFile)P.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+n.message)}return b}
function bc(){H||(H=function(a,b){this.node=b;this.bb=function(a){this.g=a;for(var b in F)if(F[b]===a){this.code=b;break}};this.bb(a);this.message=ab[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},H.prototype=Error(),H.prototype.constructor=H,[F.A].forEach(function(a){sb[a]=new H(a);sb[a].stack="<generic error, no stack>"}))}var cc;function dc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function ec(a,b,c){a=G("/dev",a);var d=dc(!!b,!!c);fc||(fc=64);var f=fc++<<8|0;lb(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,h=0;h<f;h++){try{var n=b()}catch(oa){throw new H(F.T);}if(void 0===n&&0===g)throw new H(F.na);if(null===n||void 0===n)break;g++;c[d+h]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(t){throw new H(F.T);}f&&(a.node.timestamp=Date.now());
return g}});Pb(a,d,f)}var fc,FS={},Eb,Mb,Xb,hc={};
function jc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&db(b)!==db(zb(f.node)))return-F.V;throw f;}u[c>>2]=d.dev;u[c+4>>2]=0;u[c+8>>2]=d.ino;u[c+12>>2]=d.mode;u[c+16>>2]=d.nlink;u[c+20>>2]=d.uid;u[c+24>>2]=d.gid;u[c+28>>2]=d.rdev;u[c+32>>2]=0;u[c+36>>2]=d.size;u[c+40>>2]=4096;u[c+44>>2]=d.blocks;u[c+48>>2]=d.atime.getTime()/1E3|0;u[c+52>>2]=0;u[c+56>>2]=d.mtime.getTime()/1E3|0;u[c+60>>2]=0;u[c+64>>2]=d.ctime.getTime()/1E3|0;u[c+68>>2]=0;u[c+72>>2]=d.ino;return 0}var T=0;
function U(){T+=4;return u[T-4>>2]}function V(){return D(U())}function W(){var a=N[U()];if(!a)throw new H(F.D);return a}function kc(a,b){T=b;return 0}var lc=q;q+=16;var mc,X={};function nc(a){if(0===a)return 0;a=D(a);if(!X.hasOwnProperty(a))return 0;nc.Y&&oc(nc.Y);a=X[a];var b=Ha(a)+1,c=Ea(b);c&&sa(a,A,c,b);nc.Y=c;return nc.Y}var Y=q;q+=48;var pc=Da(nb("GMT"),2);
function qc(a){a/=1E3;if((l||m)&&self.performance&&self.performance.now)for(var b=self.performance.now();self.performance.now()-b<a;);else for(b=Date.now();Date.now()-b<a;);return 0}e._usleep=qc;function rc(a){return 0===a%4&&(0!==a%100||0===a%400)}function sc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var uc=[31,29,31,30,31,30,31,31,30,31,30,31],vc=[31,28,31,30,31,30,31,31,30,31,30,31];
function wc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(rc(a.getFullYear())?uc:vc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}bc();O=Array(4096);Nb(I,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");lb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Pb("/dev/null",259);jb(1280,ob);jb(1536,pb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=p?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};ec("random",b);ec("urandom",b);R("/dev/shm");R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");
Nb({o:function(){var a=rb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=N[+c];if(!b)throw new H(F.D);a={parent:null,o:{Ca:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Sa.unshift(function(){if(!e.noFSInit&&!cc){assert(!cc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");cc=!0;bc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?ec("stdin",e.stdin):Qb("/dev/tty","/dev/stdin");e.stdout?ec("stdout",null,e.stdout):Qb("/dev/tty","/dev/stdout");e.stderr?ec("stderr",null,e.stderr):Qb("/dev/tty1","/dev/stderr");var a=S("/dev/stdin",
"r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=S("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=S("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ta.push(function(){xb=!1});Ua.push(function(){cc=!1;var a=e._fflush;a&&a(0);for(a=0;a<N.length;a++){var b=N[a];b&&Yb(b)}});Sa.unshift(function(){});Ua.push(function(){});if(p){var fs=require("fs"),tb=require("path");M.cb()}var xc,yc;
mc?(yc=u[lc>>2],xc=u[yc>>2]):(mc=!0,X.USER=X.LOGNAME="web_user",X.PATH="/",X.PWD="/",X.HOME="/home/web_user",X.LANG="C.UTF-8",X._=e.thisProgram,xc=fa(1024),yc=fa(256),u[yc>>2]=xc,u[lc>>2]=yc);var zc=[],Ac=0,Bc;for(Bc in X)if("string"===typeof X[Bc]){var Cc=Bc+"="+X[Bc];zc.push(Cc);Ac+=Cc.length}if(1024<Ac)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");
for(var Dc=0;Dc<zc.length;Dc++){for(var Ec=Cc=zc[Dc],Fc=xc,Gc=0;Gc<Ec.length;++Gc)A[Fc++>>0]=Ec.charCodeAt(Gc);A[Fc>>0]=0;u[yc+4*Dc>>2]=xc;xc+=Cc.length+1}u[yc+4*zc.length>>2]=0;r=fa(4);La=Ma=ka(q);Na=La+Pa;Oa=ka(Na);u[r>>2]=Oa;ha=!0;function nb(a,b){var c=Array(Ha(a)+1);a=sa(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=2304;e.wasmMaxTableSize=2304;e.La={};
e.Ma={abort:z,enlargeMemory:function(){ja()},getTotalMemory:function(){return w},abortOnCannotGrowMemory:ja,jsCall_i:function(a){return y[a]()},jsCall_ii:function(a,b){return y[a](b)},jsCall_iii:function(a,b,c){return y[a](b,c)},jsCall_iiii:function(a,b,c,d){return y[a](b,c,d)},jsCall_iiiii:function(a,b,c,d,f){return y[a](b,c,d,f)},jsCall_iiiiii:function(a,b,c,d,f,g){return y[a](b,c,d,f,g)},jsCall_iiiiiii:function(a,b,c,d,f,g,h){return y[a](b,c,d,f,g,h)},jsCall_iiiij:function(a,b,c,d,f){return y[a](b,
c,d,f)},jsCall_iij:function(a,b,c){return y[a](b,c)},jsCall_iiji:function(a,b,c,d){return y[a](b,c,d)},jsCall_iijii:function(a,b,c,d,f){return y[a](b,c,d,f)},jsCall_vi:function(a,b){y[a](b)},jsCall_vii:function(a,b,c){y[a](b,c)},jsCall_viii:function(a,b,c,d){y[a](b,c,d)},jsCall_viiii:function(a,b,c,d,f){y[a](b,c,d,f)},jsCall_viiiij:function(a,b,c,d,f,g){y[a](b,c,d,f,g)},jsCall_viji:function(a,b,c,d){y[a](b,c,d)},___assert_fail:function(a,b,c,d){z("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",
c,d?D(d):"unknown function"])},___setErrNo:bb,___syscall10:function(a,b){T=b;try{var c=V();Rb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||z(d),-d.g}},___syscall118:function(a,b){T=b;try{return W(),0}catch(c){return"undefined"!==typeof FS&&c instanceof H||z(c),-c.g}},___syscall140:function(a,b){T=b;try{var c=W();U();var d=U(),f=U(),g=U();Zb(c,d,g);u[f>>2]=c.position;c.ja&&0===d&&0===g&&(c.ja=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof H||z(h),-h.g}},
___syscall15:function(a,b){T=b;try{var c=V(),d=U();Ub(c,d);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall183:function(a,b){T=b;try{var c=U(),d=U();if(0===d)return-F.h;if(d<Ha("/")+1)return-F.Ga;sa("/",B,c,d);return c}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall192:function(a,b){T=b;try{var c=U(),d=U(),f=U(),g=U(),h=U(),n=U();n<<=12;a=!1;if(-1===h){var x=Hc(16384,d);if(!x)return-F.pa;Ic(x,0,d);a=!0}else{var v=N[h];if(!v)return-F.D;
b=B;if(1===(v.flags&2097155))throw new H(F.N);if(!v.f.$)throw new H(F.U);var t=v.f.$(v,b,c,d,n,f,g);x=t.$a;a=t.ga}hc[x]={Ya:x,Xa:d,ga:a,fd:h,flags:g};return x}catch(J){return"undefined"!==typeof FS&&J instanceof H||z(J),-J.g}},___syscall194:function(a,b){T=b;try{var c=U();assert(0===U());var d=U(),f=U();0<=d?assert(0===f):assert(-1===f);var g=N[c];if(!g)throw new H(F.D);if(0===(g.flags&2097155))throw new H(F.h);Wb(g.node,d);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof H||z(h),-h.g}},
___syscall195:function(a,b){T=b;try{var c=V(),d=U();return jc(Sb,c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall196:function(a,b){T=b;try{var c=V(),d=U();return jc(Tb,c,d)}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall197:function(a,b){T=b;try{var c=W(),d=U();return jc(Sb,c.path,d)}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall20:function(a,b){T=b;return 42},___syscall201:function(){return kc.apply(null,
arguments)},___syscall207:function(a,b){T=b;try{var c=U();U();U();var d=N[c];if(!d)throw new H(F.D);Vb(d.node);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall212:function(a,b){T=b;try{var c=V();U();U();Vb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||z(d),-d.g}},___syscall221:function(a,b){T=b;try{var c=W();switch(U()){case 0:var d=U();return 0>d?-F.h:S(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=
U(),c.flags|=d,0;case 12:case 12:return d=U(),wa[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-F.h;case 9:return bb(F.h),-1;default:return-F.h}}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall3:function(a,b){T=b;try{var c=W(),d=U(),f=U();return $b(c,A,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof H||z(g),-g.g}},___syscall33:function(a,b){T=b;try{var c=V();var d=U();if(d&-8)var f=-F.h;else{var g=Q(c,{I:!0}).node;a="";d&4&&(a+="r");
d&2&&(a+="w");d&1&&(a+="x");f=a&&Db(g,a)?-F.N:0}return f}catch(h){return"undefined"!==typeof FS&&h instanceof H||z(h),-h.g}},___syscall39:function(a,b){T=b;try{var c=V(),d=U();a=c;a=db(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));R(a,d);return 0}catch(f){return"undefined"!==typeof FS&&f instanceof H||z(f),-f.g}},___syscall4:function(a,b){T=b;try{var c=W(),d=U(),f=U();return ac(c,A,d,f)}catch(g){return"undefined"!==typeof FS&&g instanceof H||z(g),-g.g}},___syscall40:function(a,b){T=b;try{var c=
V(),d=Q(c,{parent:!0}).node,f=fb(c),g=L(d,f),h=Jb(d,f,!0);if(h)throw new H(h);if(!d.c.rmdir)throw new H(F.B);if(g.K)throw new H(F.O);try{P.willDeletePath&&P.willDeletePath(c)}catch(n){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+n.message)}d.c.rmdir(d,f);Cb(g);try{if(P.onDeletePath)P.onDeletePath(c)}catch(n){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+n.message)}return 0}catch(n){return"undefined"!==typeof FS&&n instanceof H||
z(n),-n.g}},___syscall5:function(a,b){T=b;try{var c=V(),d=U(),f=U();return S(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof H||z(g),-g.g}},___syscall6:function(a,b){T=b;try{var c=W();Yb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof H||z(d),-d.g}},___syscall85:function(a,b){T=b;try{var c=V(),d=U();var f=U();if(0>=f)var g=-F.h;else{var h=yb(c),n=Math.min(f,Ha(h)),x=A[d+n];sa(h,B,d,f+1);A[d+n]=x;g=n}return g}catch(v){return"undefined"!==typeof FS&&v instanceof H||z(v),
-v.g}},___syscall91:function(a,b){T=b;try{var c=U(),d=U(),f=hc[c];if(!f)return 0;if(d===f.Xa){var g=N[f.fd],h=f.flags,n=new Uint8Array(B.subarray(c,c+d));g&&g.f.aa&&g.f.aa(g,n,0,d,h);hc[c]=null;f.ga&&oc(f.Ya)}return 0}catch(x){return"undefined"!==typeof FS&&x instanceof H||z(x),-x.g}},___syscall94:function(a,b){T=b;try{var c=U(),d=U(),f=N[c];if(!f)throw new H(F.D);Ub(f.node,d);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof H||z(g),-g.g}},_emscripten_memcpy_big:function(a,b,c){B.set(B.subarray(b,
b+c),a);return a},_getenv:nc,_gettimeofday:function(a){var b=Date.now();u[a>>2]=b/1E3|0;u[a+4>>2]=b%1E3*1E3|0;return 0},_gmtime:function(a){a=new Date(1E3*u[a>>2]);u[Y>>2]=a.getUTCSeconds();u[Y+4>>2]=a.getUTCMinutes();u[Y+8>>2]=a.getUTCHours();u[Y+12>>2]=a.getUTCDate();u[Y+16>>2]=a.getUTCMonth();u[Y+20>>2]=a.getUTCFullYear()-1900;u[Y+24>>2]=a.getUTCDay();u[Y+36>>2]=0;u[Y+32>>2]=0;u[Y+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;u[Y+40>>2]=pc;return Y},_llvm_trap:function(){z("trap!")},
_nanosleep:function(a,b){var c=u[a>>2];a=u[a+4>>2];0!==b&&(u[b>>2]=0,u[b+4>>2]=0);return qc(1E6*c+a/1E3)},_sqlite3AlterBeginAddColumn:function(){e.printErr("missing function: sqlite3AlterBeginAddColumn");z(-1)},_sqlite3AlterFinishAddColumn:function(){e.printErr("missing function: sqlite3AlterFinishAddColumn");z(-1)},_sqlite3AlterRenameTable:function(){e.printErr("missing function: sqlite3AlterRenameTable");z(-1)},_sqlite3Analyze:function(){e.printErr("missing function: sqlite3Analyze");z(-1)},_sqlite3Attach:function(){e.printErr("missing function: sqlite3Attach");
z(-1)},_sqlite3CreateView:function(){e.printErr("missing function: sqlite3CreateView");z(-1)},_sqlite3Detach:function(){e.printErr("missing function: sqlite3Detach");z(-1)},_sqlite3Pragma:function(){e.printErr("missing function: sqlite3Pragma");z(-1)},_sqlite3Reindex:function(){e.printErr("missing function: sqlite3Reindex");z(-1)},_sqlite3Vacuum:function(){e.printErr("missing function: sqlite3Vacuum");z(-1)},_sqlite3VtabArgExtend:function(){e.printErr("missing function: sqlite3VtabArgExtend");z(-1)},
_sqlite3VtabArgInit:function(){e.printErr("missing function: sqlite3VtabArgInit");z(-1)},_sqlite3VtabBeginParse:function(){e.printErr("missing function: sqlite3VtabBeginParse");z(-1)},_sqlite3VtabFinishParse:function(){e.printErr("missing function: sqlite3VtabFinishParse");z(-1)},_strftime:function(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=
c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function n(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function x(a){a=wc(new Date(a.m+1900,0,1),a.ea);var b=n(new Date(a.getFullYear()+
1,0,4));return 0>=h(n(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var v=u[d+40>>2];d={gb:u[d>>2],fb:u[d+4>>2],da:u[d+8>>2],J:u[d+12>>2],G:u[d+16>>2],m:u[d+20>>2],Da:u[d+24>>2],ea:u[d+28>>2],Kd:u[d+32>>2],eb:u[d+36>>2],hb:v?D(v):""};c=D(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var t in v)c=c.replace(new RegExp(t,"g"),v[t]);var J=
"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),oa="January February March April May June July August September October November December".split(" ");v={"%a":function(a){return J[a.Da].substring(0,3)},"%A":function(a){return J[a.Da]},"%b":function(a){return oa[a.G].substring(0,3)},"%B":function(a){return oa[a.G]},"%C":function(a){return g((a.m+1900)/100|0,2)},"%d":function(a){return g(a.J,2)},"%e":function(a){return f(a.J,2," ")},"%g":function(a){return x(a).toString().substring(2)},
"%G":function(a){return x(a)},"%H":function(a){return g(a.da,2)},"%I":function(a){a=a.da;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.J+sc(rc(a.m+1900)?uc:vc,a.G-1),3)},"%m":function(a){return g(a.G+1,2)},"%M":function(a){return g(a.fb,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.da&&12>a.da?"AM":"PM"},"%S":function(a){return g(a.gb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.m+1900,a.G+1,a.J,0,0,0,0)).getDay()||7},"%U":function(a){var b=
new Date(a.m+1900,0,1),c=0===b.getDay()?b:wc(b,7-b.getDay());a=new Date(a.m+1900,a.G,a.J);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(sc(rc(a.getFullYear())?uc:vc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=n(new Date(a.m+1900,0,4)),c=n(new Date(a.m+1901,0,4)),d=wc(new Date(a.m+1900,0,1),a.ea);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.m+1900?a.ea+32-b.getDate():a.ea+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.m+1900,a.G+
1,a.J,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.m,0,1),c=1===b.getDay()?b:wc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.m+1900,a.G,a.J);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(sc(rc(a.getFullYear())?uc:vc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.m+1900).toString().substring(2)},"%Y":function(a){return a.m+1900},"%z":function(a){a=a.eb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.hb},
"%%":function(){return"%"}};for(t in v)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),v[t](d)));t=nb(c,!1);if(t.length>b)return 0;A.set(t,a);return t.length-1},_sysconf:function(a){switch(a){case 30:return 16384;case 85:return B.length/16384;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 79:return 0;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}bb(F.h);return-1},
_time:function(a){var b=Date.now()/1E3|0;a&&(u[a>>2]=b);return b},_utimes:function(a,b){if(b){var c=1E3*u[b+8>>2];c+=u[b+12>>2]/1E3}else c=Date.now();a=D(a);try{b=c;var d=Q(a,{I:!0}).node;d.c.l(d,{timestamp:Math.max(b,c)});return 0}catch(f){a=f;if(!(a instanceof H)){a+=" : ";a:{d=Error();if(!d.stack){try{throw Error(0);}catch(g){d=g}if(!d.stack){d="(no stack trace available)";break a}}d=d.stack.toString()}e.extraStackTrace&&(d+="\n"+e.extraStackTrace());d=Ia(d);throw a+d;}bb(a.g);return-1}},DYNAMICTOP_PTR:r,
STACKTOP:Ma};var Jc=e.asm(e.La,e.Ma,buffer);e.asm=Jc;e._RegisterExtensionFunctions=function(){return e.asm._RegisterExtensionFunctions.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};
var oc=e._free=function(){return e.asm._free.apply(null,arguments)},Ea=e._malloc=function(){return e.asm._malloc.apply(null,arguments)},Hc=e._memalign=function(){return e.asm._memalign.apply(null,arguments)},Ic=e._memset=function(){return e.asm._memset.apply(null,arguments)};e._sqlite3_bind_blob=function(){return e.asm._sqlite3_bind_blob.apply(null,arguments)};e._sqlite3_bind_double=function(){return e.asm._sqlite3_bind_double.apply(null,arguments)};
e._sqlite3_bind_int=function(){return e.asm._sqlite3_bind_int.apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return e.asm._sqlite3_bind_parameter_index.apply(null,arguments)};e._sqlite3_bind_text=function(){return e.asm._sqlite3_bind_text.apply(null,arguments)};e._sqlite3_changes=function(){return e.asm._sqlite3_changes.apply(null,arguments)};e._sqlite3_clear_bindings=function(){return e.asm._sqlite3_clear_bindings.apply(null,arguments)};
e._sqlite3_close_v2=function(){return e.asm._sqlite3_close_v2.apply(null,arguments)};e._sqlite3_column_blob=function(){return e.asm._sqlite3_column_blob.apply(null,arguments)};e._sqlite3_column_bytes=function(){return e.asm._sqlite3_column_bytes.apply(null,arguments)};e._sqlite3_column_double=function(){return e.asm._sqlite3_column_double.apply(null,arguments)};e._sqlite3_column_name=function(){return e.asm._sqlite3_column_name.apply(null,arguments)};
e._sqlite3_column_text=function(){return e.asm._sqlite3_column_text.apply(null,arguments)};e._sqlite3_column_type=function(){return e.asm._sqlite3_column_type.apply(null,arguments)};e._sqlite3_create_function_v2=function(){return e.asm._sqlite3_create_function_v2.apply(null,arguments)};e._sqlite3_data_count=function(){return e.asm._sqlite3_data_count.apply(null,arguments)};e._sqlite3_errmsg=function(){return e.asm._sqlite3_errmsg.apply(null,arguments)};
e._sqlite3_exec=function(){return e.asm._sqlite3_exec.apply(null,arguments)};e._sqlite3_finalize=function(){return e.asm._sqlite3_finalize.apply(null,arguments)};e._sqlite3_free=function(){return e.asm._sqlite3_free.apply(null,arguments)};e._sqlite3_open=function(){return e.asm._sqlite3_open.apply(null,arguments)};e._sqlite3_prepare_v2=function(){return e.asm._sqlite3_prepare_v2.apply(null,arguments)};e._sqlite3_reset=function(){return e.asm._sqlite3_reset.apply(null,arguments)};
e._sqlite3_result_double=function(){return e.asm._sqlite3_result_double.apply(null,arguments)};e._sqlite3_result_null=function(){return e.asm._sqlite3_result_null.apply(null,arguments)};e._sqlite3_result_text=function(){return e.asm._sqlite3_result_text.apply(null,arguments)};e._sqlite3_step=function(){return e.asm._sqlite3_step.apply(null,arguments)};e._sqlite3_value_blob=function(){return e.asm._sqlite3_value_blob.apply(null,arguments)};
e._sqlite3_value_bytes=function(){return e.asm._sqlite3_value_bytes.apply(null,arguments)};e._sqlite3_value_double=function(){return e.asm._sqlite3_value_double.apply(null,arguments)};e._sqlite3_value_int=function(){return e.asm._sqlite3_value_int.apply(null,arguments)};e._sqlite3_value_text=function(){return e.asm._sqlite3_value_text.apply(null,arguments)};e._sqlite3_value_type=function(){return e.asm._sqlite3_value_type.apply(null,arguments)};
var ra=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)},qa=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},pa=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.asm=Jc;
e.cwrap=function(a,b,c){c=c||[];var d=na(a),f=c.every(function(a){return"number"===a});return"string"!==b&&f?d:function(){var d=c,f=arguments,n=na(a),x=[],v=0;if(f)for(var t=0;t<f.length;t++){var J=ua[d[t]];J?(0===v&&(v=pa()),x[t]=J(f[t])):x[t]=f[t]}d=n.apply(null,x);"string"===b&&(d=D(d));0!==v&&qa(v);return d}};e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};
function ea(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ea.prototype=Error();ea.prototype.constructor=ea;Za=function Kc(){e.calledRun||Mc();e.calledRun||(Za=Kc)};
function Mc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!ma)){Wa||(Wa=!0,Qa(Sa));Qa(Ta);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Va.unshift(a)}Qa(Va)}}if(!(0<E)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Xa();Qa(Ra);0<E||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=Mc;e.exit=function(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(ma=!0,Ma=void 0,Qa(Ua),e.onExit))e.onExit(a);p&&process.exit(a);e.quit(a,new ea(a))}};function z(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";ma=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=z;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;Mc();
var Z;Z={X:0,Yc:1,rd:2,Bd:3,jb:4,lb:5,ud:6,NOMEM:7,Ed:8,sd:9,td:10,ob:11,NOTFOUND:12,qd:13,mb:14,Cd:15,EMPTY:16,Fd:17,Gd:18,nb:19,vd:20,wd:21,xd:22,kb:23,pd:24,Dd:25,yd:26,zd:27,Hd:28,Ia:100,DONE:101,Ha:1,FLOAT:2,Ja:3,Ea:4,Ad:5,Ka:1};
e.onRuntimeInitialized=function(){var a=ra(4);var b=function(){function a(a,b){this.j=a;this.db=b;this.C=1;this.ha=[]}a.prototype.bind=function(a){if(!this.j)throw"Statement closed";this.reset();return Array.isArray(a)?this.Oa(a):this.Pa(a)};a.prototype.step=function(){var a;if(!this.j)throw"Statement closed";this.C=1;switch(a=kb(this.j)){case Z.Ia:return!0;case Z.DONE:return!1;default:return this.db.handleError(a)}};a.prototype.Va=function(a){null==a&&(a=this.C++);return Lc(this.j,a)};a.prototype.Wa=
function(a){null==a&&(a=this.C++);return Nc(this.j,a)};a.prototype.getBlob=function(a){var b;null==a&&(a=this.C++);var c=Oc(this.j,a);var d=Pc(this.j,a);var f=new Uint8Array(c);for(a=b=0;0<=c?b<c:b>c;a=0<=c?++b:--b)f[a]=A[d+a];return f};a.prototype.get=function(a){var b,c;null!=a&&this.bind(a)&&this.step();var d=[];a=b=0;for(c=ic(this.j);0<=c?b<c:b>c;a=0<=c?++b:--b)switch(Qc(this.j,a)){case Z.Ha:case Z.FLOAT:d.push(this.Va(a));break;case Z.Ja:d.push(this.Wa(a));break;case Z.Ea:d.push(this.getBlob(a));
break;default:d.push(null)}return d};a.prototype.getColumnNames=function(){var a,b;var c=[];var d=a=0;for(b=ic(this.j);0<=b?a<b:a>b;d=0<=b?++a:--a)c.push(Rc(this.j,d));return c};a.prototype.getAsObject=function(a){var b,c;var d=this.get(a);var f=this.getColumnNames();var g={};a=b=0;for(c=f.length;b<c;a=++b){var h=f[a];g[h]=d[a]}return g};a.prototype.run=function(a){null!=a&&this.bind(a);this.step();return this.reset()};a.prototype.Sa=function(a,b){var c;null==b&&(b=this.C++);a=nb(a);this.ha.push(c=
Da(a,0));this.db.handleError(v(this.j,b,c,a.length-1,0))};a.prototype.Na=function(a,b){var c;null==b&&(b=this.C++);this.ha.push(c=Da(a,0));this.db.handleError(t(this.j,b,c,a.length,0))};a.prototype.Ra=function(a,b){null==b&&(b=this.C++);this.db.handleError((a===(a|0)?oa:J)(this.j,b,a))};a.prototype.Qa=function(a){null==a&&(a=this.C++);t(this.j,a,0,0,0)};a.prototype.ta=function(a,b){null==b&&(b=this.C++);switch(typeof a){case "string":this.Sa(a,b);break;case "number":case "boolean":this.Ra(a+0,b);
break;case "object":if(null===a)this.Qa(b);else if(null!=a.length)this.Na(a,b);else throw"Wrong API use : tried to bind a value of an unknown type ("+a+").";}};a.prototype.Pa=function(a){var b;for(b in a){var c=a[b];var d=Ib(this.j,b);0!==d&&this.ta(c,d)}return!0};a.prototype.Oa=function(a){var b,c;var d=b=0;for(c=a.length;b<c;d=++b){var f=a[d];this.ta(f,d+1)}return!0};a.prototype.reset=function(){this.freemem();return Sc(this.j)===Z.X&&Tc(this.j)===Z.X};a.prototype.freemem=function(){for(var a;a=
this.ha.pop();)oc(a);return null};a.prototype.free=function(){this.freemem();var a=Uc(this.j)===Z.X;delete this.db.ba[this.j];this.j=0;return a};return a}();var c=function(){function c(b){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=b){var c=this.filename,f=c?G("/",c):"/";c=dc(!0,!0);f=Ob(f,(void 0!==c?c:438)&4095|32768,0);if(b){if("string"===typeof b){for(var g=Array(b.length),h=0,n=b.length;h<n;++h)g[h]=b.charCodeAt(h);b=g}Ub(f,c|146);g=S(f,"w");ac(g,b,0,b.length,0,void 0);Yb(g);
Ub(f,c)}}this.handleError(d(this.filename,a));this.db=C(a,"i32");Vc(this.db);this.ba={}}c.prototype.run=function(b,c){if(!this.db)throw"Database closed";c?(b=this.prepare(b,c),b.step(),b.free()):this.handleError(g(this.db,b,0,0,a));return this};c.prototype.exec=function(c){if(!this.db)throw"Database closed";var d=pa();var f=c.length<<3;var g=ra(f);sa(c,B,g,f);c=ra(4);for(f=[];0!==C(g,"i8");){va(a);va(c);this.handleError(x(this.db,g,-1,a,c));var h=C(a,"i32");g=C(c,"i32");if(0!==h){var n=new b(h,this);
for(h=null;n.step();)null===h&&(h={columns:n.getColumnNames(),values:[]},f.push(h)),h.values.push(n.get());n.free()}}qa(d);return f};c.prototype.each=function(a,b,c,d){"function"===typeof b&&(d=c,c=b,b=void 0);for(a=this.prepare(a,b);a.step();)c(a.getAsObject());a.free();if("function"===typeof d)return d()};c.prototype.prepare=function(c,d){va(a);this.handleError(n(this.db,c,-1,a,0));c=C(a,"i32");if(0===c)throw"Nothing to prepare";var f=new b(c,this);null!=d&&f.bind(d);return this.ba[c]=f};c.prototype["export"]=
function(){var b;var c=this.ba;for(h in c){var g=c[h];g.free()}this.handleError(f(this.db));g=this.filename;var h=h={encoding:"binary"};h.flags=h.flags||"r";h.encoding=h.encoding||"binary";if("utf8"!==h.encoding&&"binary"!==h.encoding)throw Error('Invalid encoding type "'+h.encoding+'"');c=S(g,h.flags);g=Sb(g).size;var n=new Uint8Array(g);$b(c,n,0,g,0);"utf8"===h.encoding?b=Fa(n,0):"binary"===h.encoding&&(b=n);Yb(c);this.handleError(d(this.filename,a));this.db=C(a,"i32");return b};c.prototype.close=
function(){var a;var b=this.ba;for(a in b){var c=b[a];c.free()}this.handleError(f(this.db));Rb("/"+this.filename);return this.db=null};c.prototype.handleError=function(a){if(a===Z.X)return null;a=tc(this.db);throw Error(a);};c.prototype.getRowsModified=function(){return h(this.db)};c.prototype.create_function=function(a,b){var c=la(function(a,c,d){var f,g;var h=[];for(f=g=0;0<=c?g<c:g>c;f=0<=c?++g:--g){var n=C(d+4*f,"i32");var t=Wc(n);f=function(){switch(!1){case 1!==t:return Xc;case 2!==t:return Yc;
case 3!==t:return Zc;case 4!==t:return function(a){var b,c;var d=$c(a);var f=ad(a);a=new Uint8Array(d);for(b=c=0;0<=d?c<d:c>d;b=0<=d?++c:--c)a[b]=A[f+b];return a};default:return function(){return null}}}();f=f(n);h.push(f)}if(c=b.apply(null,h))switch(typeof c){case "number":return bd(a,c);case "string":return cd(a,c,-1,-1)}else return dd(a)});this.handleError(ed(this.db,a,b.length,Z.Ka,0,c,0,0,0));return this};return c}();var d=e.cwrap("sqlite3_open","number",["string","number"]);var f=e.cwrap("sqlite3_close_v2",
"number",["number"]);var g=e.cwrap("sqlite3_exec","number",["number","string","number","number","number"]);e.cwrap("sqlite3_free","",["number"]);var h=e.cwrap("sqlite3_changes","number",["number"]);var n=e.cwrap("sqlite3_prepare_v2","number",["number","string","number","number","number"]);var x=e.cwrap("sqlite3_prepare_v2","number",["number","number","number","number","number"]);var v=e.cwrap("sqlite3_bind_text","number",["number","number","number","number","number"]);var t=e.cwrap("sqlite3_bind_blob",
"number",["number","number","number","number","number"]);var J=e.cwrap("sqlite3_bind_double","number",["number","number","number"]);var oa=e.cwrap("sqlite3_bind_int","number",["number","number","number"]);var Ib=e.cwrap("sqlite3_bind_parameter_index","number",["number","string"]);var kb=e.cwrap("sqlite3_step","number",["number"]);var tc=e.cwrap("sqlite3_errmsg","string",["number"]);var ic=e.cwrap("sqlite3_data_count","number",["number"]);var Lc=e.cwrap("sqlite3_column_double","number",["number","number"]);
var Nc=e.cwrap("sqlite3_column_text","string",["number","number"]);var Pc=e.cwrap("sqlite3_column_blob","number",["number","number"]);var Oc=e.cwrap("sqlite3_column_bytes","number",["number","number"]);var Qc=e.cwrap("sqlite3_column_type","number",["number","number"]);var Rc=e.cwrap("sqlite3_column_name","string",["number","number"]);var Tc=e.cwrap("sqlite3_reset","number",["number"]);var Sc=e.cwrap("sqlite3_clear_bindings","number",["number"]);var Uc=e.cwrap("sqlite3_finalize","number",["number"]);
var ed=e.cwrap("sqlite3_create_function_v2","number","number string number number number number number number number".split(" "));var Wc=e.cwrap("sqlite3_value_type","number",["number"]);var $c=e.cwrap("sqlite3_value_bytes","number",["number"]);var Zc=e.cwrap("sqlite3_value_text","string",["number"]);var Xc=e.cwrap("sqlite3_value_int","number",["number"]);var ad=e.cwrap("sqlite3_value_blob","number",["number"]);var Yc=e.cwrap("sqlite3_value_double","number",["number"]);var bd=e.cwrap("sqlite3_result_double",
"",["number","number"]);var dd=e.cwrap("sqlite3_result_null","",["number"]);var cd=e.cwrap("sqlite3_result_text","",["number","string","number","number"]);var Vc=e.cwrap("RegisterExtensionFunctions","number",["number"]);return e.SQL={Database:c}};this.SQL=e;


  return SQL;
};
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = SQL;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return SQL; });
else if (typeof exports === 'object')
  exports["SQL"] = SQL;
